import json,pathlib,copy
B=pathlib.Path('Packages/contracts'); F=B/'fixtures'
def dump(fam,name,v):
 p=F/fam/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
U=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444','55555555-5555-4555-8555-555555555555','66666666-6666-4666-8666-666666666666','77777777-7777-4777-8777-777777777777','88888888-8888-4888-8888-888888888888','99999999-9999-4999-8999-999999999999']
H=['0'*64,'1'*64,'2'*64,'3'*64]
pins={'coreVersion':'vox-core-contract-only','rendererRevision':'swift-legacy-m0','profileID':'apple-parity-v1','profileVersion':1}
route={'attachmentFolder':['Assets'],'collisionPolicy':'reuseIfHashMatches','extensionPolicy':'markdownDotMd','logicalFolder':['Synthetic Vault','Inbox'],'noteNameTemplate':'capture-{id}.md'}
meta={'finalNewline':True,'frontmatterMode':'merge','lineEnding':'lf','orderedFields':[{'name':'source','value':'synthetic'}],'templatePolicy':'frozenObservation'}
dest={'capabilityClass':'userVault','capabilityReference':'synthetic-vault-capability','expectedCaseSensitivity':'unknown'}
preset={'destinationPolicy':dest,'id':U[2],'metadataPolicy':meta,'retryMarkerPolicy':'voxCaptureCommentV1','revision':7,'routePolicy':route,'snapshotHash':H[0],'templateFreezePoint':'firstPreparation'}
prep={'calendar':'gregorian','captureSource':'app','contractVersion':1,'createdAtEpochMilliseconds':1700000000000,'invocation':{'locationOutcome':'notRequested','originRecordingID':None,'sequence':1},'locale':'en-US','operation':'newNote','payloads':[{'id':U[1],'kind':'text','text':'Synthetic capture text.'},{'id':U[3],'kind':'link','label':'Synthetic link','url':'https://example.invalid/synthetic'},{'id':U[4],'kind':'asset','length':32,'mediaType':'audio/wav','originalNamePolicy':'discard','safeExtension':'wav','sha256':H[1],'sourceID':U[5]}],'pins':pins,'preset':preset,'requestID':U[0],'timezone':'America/Los_Angeles'}
for p in F.glob('*/*.json'): p.unlink()
dump('capture-preparation-input','valid-complete.json',prep)
x=copy.deepcopy(prep);x['payloads'][0]['unexpected']=True;dump('capture-preparation-input','invalid-unknown-payload-field.json',x)
x=copy.deepcopy(prep);x['payloads'][1]['kind']='text';dump('capture-preparation-input','invalid-tag-payload-mismatch.json',x)
x=copy.deepcopy(prep);x['preset']['routePolicy']['logicalFolder'][0]='..';dump('capture-preparation-input','invalid-unsafe-path.json',x)
x=copy.deepcopy(prep);x['payloads'][2]['length']=1073741825;dump('capture-preparation-input','invalid-asset-oversize.json',x)
req={'aggregateMaximumBytes':268435456,'contractVersion':1,'observations':[{'id':U[3],'kind':'candidateOccupancy','logicalCandidates':[['Synthetic Vault','Inbox','capture.md']]},{'id':U[4],'kind':'frozenTemplate','maximumBytes':268435456,'required':False,'templateCapabilityReference':'synthetic-template'},{'id':U[5],'kind':'existingNote','logicalPath':['Synthetic Vault','Inbox','capture.md'],'maximumBytes':268435456,'required':True},{'id':U[6],'kind':'stagedAssetMetadata','sourceIDs':[U[5]]}],'ordering':'listed','preparationRevision':1,'requestID':U[0],'snapshotHash':H[0]}
dump('required-observations','valid-all-kinds.json',req)
x=copy.deepcopy(req);x['observations'][0]['maximumBytes']=1;dump('required-observations','invalid-tag-request-mismatch.json',x)
x=copy.deepcopy(req);x['observations'].append(copy.deepcopy(x['observations'][0]));dump('required-observations','invalid-duplicate-id.json',x)
mat={'calendar':'gregorian','captureSource':'app','contractVersion':1,'controlByteCount':4096,'createdAtEpochMilliseconds':1700000000000,'locale':'en-US','observations':[{'kind':'candidateOccupancy','logicalPaths':[['Synthetic Vault','Inbox','capture.md']],'observationID':U[3],'orderedSetHash':H[1],'status':'present'},{'byteStreamID':None,'kind':'frozenTemplate','length':0,'observationID':U[4],'sha256':H[0],'status':'absent'},{'byteStreamID':U[7],'kind':'existingNote','length':25,'logicalPath':['Synthetic Vault','Inbox','capture.md'],'observationID':U[5],'sha256':H[2],'status':'present'},{'assets':[{'length':32,'mediaType':'audio/wav','sha256':H[1],'sourceID':U[5]}],'kind':'stagedAssetMetadata','observationID':U[6],'orderedSetHash':H[3],'status':'present'}],'operation':'newNote','payloads':prep['payloads'],'pins':pins,'preparationRevision':1,'preset':preset,'requestID':U[0],'session':{'inputOrdering':'observation-list-then-sequence','maximumAggregateObservationBytes':268435456,'maximumChunkBytes':1048576,'singleFinalize':True,'singleSeal':True},'snapshotHash':H[0],'timezone':'America/Los_Angeles'}
dump('capture-materialization-input','valid-complete.json',mat)
x=copy.deepcopy(mat);x['observations'][1]['status']='present';dump('capture-materialization-input','invalid-present-template-null-stream.json',x)
x=copy.deepcopy(mat);x['observations'][0]['kind']='existingNote';dump('capture-materialization-input','invalid-tag-observation-mismatch.json',x)
x=copy.deepcopy(mat);x['controlByteCount']=1048577;dump('capture-materialization-input','invalid-control-oversize.json',x)
x=copy.deepcopy(mat);x['session']['maximumChunkBytes']=1048575;dump('capture-materialization-input','invalid-session-chunk-limit.json',x)
plan={'artifacts':[{'artifactID':U[4],'commitSequence':0,'equivalenceRule':'sameSourceAndResultHash','expectedExistingPolicy':'absent','expectedExistingSHA256':None,'journalFrontier':'attachmentVerified','kind':'attachment','logicalPath':['Synthetic Vault','Assets','audio.wav'],'mediaType':'audio/wav','operationID':U[6],'receiptKind':'attachmentCommit','resultLength':32,'resultSHA256':H[1],'sourceID':U[5],'sourceLength':32,'sourceMediaType':'audio/wav','sourceSHA256':H[1]},{'artifactID':U[7],'commitSequence':1,'equivalenceRule':'exactBytes','expectedExistingPolicy':'hashMatch','expectedExistingSHA256':H[2],'expectedOriginalSHA256':H[2],'journalFrontier':'noteVerified','kind':'note','logicalPath':['Synthetic Vault','Inbox','capture.md'],'mediaType':'text/markdown; charset=utf-8','operationID':U[8],'preparedStreamID':U[3],'receiptKind':'noteCommit','resultLength':25,'resultSHA256':H[3],'writeMode':'append'}],'contractVersion':1,'diagnostics':[{'code':'materialized','fieldPath':'$','severity':'info'}],'operation':'existingNoteAppend','pins':pins,'planHash':H[0],'preparedByteDelivery':{'finalJSONDuplicatesBytes':False,'maximumChunkBytes':1048576,'mode':'drainedImmutableArtifacts'},'requestID':U[0],'retryMarker':{'placement':'entrySuffixBeforeFinalNewline','policy':'voxCaptureCommentV1','syntax':'<!-- vox-capture:{lowercase-uuid} -->'},'warnings':[]}
dump('artifact-plan','valid-complete.json',plan)
x=copy.deepcopy(plan);x['artifacts'][0]['kind']='note';dump('artifact-plan','invalid-tag-artifact-mismatch.json',x)
x=copy.deepcopy(plan);x['retryMarker']['syntax']='<!-- vox-operation:{lowercase-uuid} -->';dump('artifact-plan','invalid-marker-syntax.json',x)
x=copy.deepcopy(plan);x['artifacts'][1]['commitSequence']=0;dump('artifact-plan','invalid-commit-order.json',x)
x=copy.deepcopy(plan);x['preparedByteDelivery']['finalJSONDuplicatesBytes']=True;dump('artifact-plan','invalid-final-json-byte-duplication.json',x)
# Wear fixtures from schema variant examples.
base={'protocolVersion':1,'messageID':U[1],'recordingID':U[0],'senderInstallationID':U[2],'deviceID':U[3],'epoch':1,'revision':1,'correlationID':U[4]}
portable={'destinationCapabilityReference':'synthetic-vault-capability','localASRPolicy':'requiredLocal','locationPolicy':'excluded','metadataPolicy':meta,'operation':'newNote','recordingOnlyFilenamePolicyReference':None,'recordingOnlyFolderPolicyReference':None,'routePolicy':route}
payloads={
'capabilityHello':{'supportedVersions':[1],'capabilities':['assets','channels']},'unsupportedVersion':{'reasonCode':'unsupportedProtocolVersion','receivedVersion':2,'supportedVersions':[1]},'presetInventory':{'inventoryRevision':7,'presets':[{'presetID':U[5],'revision':7,'snapshotHash':H[0]}]},'presetSnapshot':{'portablePolicy':portable,'presetID':U[5],'presetRevision':7,'schemaVersion':1,'snapshotHash':H[0]},'recordingMetadata':{'createdAtEpochMilliseconds':1700000000000,'localASRPolicy':'requiredLocal','locationPolicy':'excluded','mode':'transcript','presetID':U[5],'presetRevision':7,'presetSnapshotHash':H[0],'recordingOnlyFilenamePolicyReference':None,'recordingOnlyFolderPolicyReference':None,'timezone':'UTC'},'assetManifest':{'assetID':U[6],'length':1048576,'mediaType':'audio/wav','sha256':H[1],'transport':'dataAsset'},'transferFrontier':{'assetID':U[6],'assetLength':1048576,'assetSHA256':H[1],'chunkLength':1048576,'chunkSequence':0,'durableOffset':1048576,'frontierRevision':1},'reconciliationSummary':{'pendingActionCorrelationIDs':[],'recordings':[{'lastRevision':1,'recordingID':U[0],'state':'localRecorded'}]},'transferReceipt':{'assetID':U[6],'durableOffset':1048576,'frontierRevision':1,'transportReceiptID':U[7]},'phoneIngested':{'assetLength':1048576,'assetSHA256':H[1],'durableReceiptID':U[7],'phonePackageHash':H[2]},'vaultCommitted':{'destinationReceiptID':U[7],'phoneIngestedCorrelationID':U[4],'verifiedArtifactHash':H[3],'verifiedArtifactLength':1048576},'terminalFailure':{'failedMessageCorrelationID':U[4],'mediaRetained':True,'reasonCode':'permanentDestinationFailure'},'discarded':{'actionReceiptID':U[7],'discardReason':'explicitUserDiscard','mediaDeletionPersisted':True},'sourceDeletionAuthorized':{'authorizationThreshold':'vaultCommitted','durableObservationReceiptID':U[7],'vaultCommitCorrelationID':U[4]},'reassign':{'actionID':U[7],'targetCapabilityReference':'synthetic-vault-2','userConfirmed':True},'retry':{'actionID':U[7],'retryFromRevision':1,'userInitiated':True},'discard':{'actionID':U[7],'retentionOverride':'explicitDiscard','userConfirmed':True}}
replay={'capabilityHello':'idempotent','unsupportedVersion':'terminal','presetInventory':'newerRevisionWins','presetSnapshot':'newerRevisionWins','recordingMetadata':'newerRevisionWins','assetManifest':'newerRevisionWins','transferFrontier':'newerRevisionWins','reconciliationSummary':'newerRevisionWins','transferReceipt':'idempotent','phoneIngested':'idempotent','vaultCommitted':'terminal','terminalFailure':'terminal','discarded':'terminal','sourceDeletionAuthorized':'terminal','reassign':'idempotent','retry':'idempotent','discard':'terminal'}
messages={}
for i,(kind,pay) in enumerate(payloads.items()):
 e={**base,'messageID':f'{i+1:08x}-1111-4111-8111-111111111111','messageKind':kind,'payload':pay,'replayRule':replay[kind],'revision':i+1};messages[kind]=e;dump('wearable-protocol',f'valid-{kind}.json',e)
for kind,field,bad,name in [('recordingMetadata','localASRPolicy','disabled','invalid-recording-mode-policy.json'),('transferFrontier','chunkLength',1048577,'invalid-frontier-chunk-oversize.json'),('sourceDeletionAuthorized','authorizationThreshold','phoneIngested','invalid-deletion-threshold.json')]:
 x=copy.deepcopy(messages[kind]);x['payload'][field]=bad;dump('wearable-protocol',name,x)
x=copy.deepcopy(messages['phoneIngested']);x['payload']['verifiedArtifactHash']=H[3];dump('wearable-protocol','invalid-kind-payload-cross-contamination.json',x)
# correlated traces
seq=[]
for kind,rev,corr in [('recordingMetadata',1,U[4]),('assetManifest',2,U[4]),('transferFrontier',3,U[4]),('transferReceipt',4,U[4]),('phoneIngested',5,U[4]),('vaultCommitted',6,U[4]),('sourceDeletionAuthorized',7,U[4])]:
 e=copy.deepcopy(messages[kind]);e['revision']=rev;e['correlationID']=corr;seq.append(e)
trace={'envelopes':seq,'expectedDeletionPermitted':True,'expectedFinalState':'sourceDeletionAuthorized','traceID':U[8],'traceVersion':1}
dump('wearable-protocol-trace','valid-ingest-commit-delete.json',trace)
for name,mut in [('invalid-delete-before-vault.json',lambda x:x['envelopes'].insert(5,x['envelopes'].pop(6))),('invalid-sender-change.json',lambda x:x['envelopes'][3].update(senderInstallationID=U[8])),('invalid-revision-regression.json',lambda x:x['envelopes'][4].update(revision=2)),('invalid-correlation-change.json',lambda x:x['envelopes'][4].update(correlationID=U[8])),('invalid-terminal-followup.json',lambda x:x['envelopes'].append(copy.deepcopy(messages['retry']))),('invalid-ack-without-ingest.json',lambda x:x['envelopes'].pop(4))]:
 x=copy.deepcopy(trace);mut(x);dump('wearable-protocol-trace',name,x)
