#!/usr/bin/env python3
"""Human-reviewed translations for strings exercised by screenshot stories.

These overrides replace ambiguous short-label output from the offline
statistical translator. Keep the locale order stable: ``values`` validates
that every source phrase has one translation for every non-English runtime
locale.
"""

from __future__ import annotations


NON_ENGLISH_LOCALES = (
    "ar", "bn", "de", "es", "fr", "hi", "id", "it", "ja", "ko", "nl",
    "pl", "pt-BR", "ru", "ta", "th", "tr", "uk", "ur", "vi", "zh-Hans",
    "zh-Hant",
)


def values(*translations: str) -> dict[str, str]:
    if len(translations) != len(NON_ENGLISH_LOCALES):
        raise ValueError(
            f"expected {len(NON_ENGLISH_LOCALES)} translations, got {len(translations)}"
        )
    return dict(zip(NON_ENGLISH_LOCALES, translations))


SCREENSHOT_REVIEWED_OVERRIDES = {
    "Live": values(
        "مباشر", "লাইভ", "Live", "En directo", "En direct", "लाइव", "Langsung",
        "In diretta", "ライブ", "실시간", "Live", "Na żywo", "Ao vivo", "В эфире",
        "நேரலை", "สด", "Canlı", "Наживо", "لائیو", "Trực tiếp", "实时", "即時",
    ),
    "Sent": values(
        "تم الإرسال", "পাঠানো হয়েছে", "Gesendet", "Enviado", "Envoyé", "भेजा गया",
        "Terkirim", "Inviato", "送信済み", "전송됨", "Verzonden", "Wysłano", "Enviado",
        "Отправлено", "அனுப்பப்பட்டது", "ส่งแล้ว", "Gönderildi", "Надіслано",
        "بھیج دیا گیا", "Đã gửi", "已发送", "已傳送",
    ),
    "Ready": values(
        "جاهز", "প্রস্তুত", "Bereit", "Listo", "Prêt", "तैयार", "Siap", "Pronto",
        "準備完了", "준비됨", "Gereed", "Gotowe", "Pronto", "Готово", "தயார்", "พร้อม",
        "Hazır", "Готово", "تیار", "Sẵn sàng", "准备就绪", "準備就緒",
    ),
    "Voice Capture": values(
        "تسجيل صوتي", "ভয়েস ক্যাপচার", "Sprachaufnahme", "Captura de voz", "Capture vocale",
        "वॉइस कैप्चर", "Rekam Suara", "Acquisizione vocale", "音声キャプチャ", "음성 캡처",
        "Spraakopname", "Przechwytywanie głosu", "Captura de voz", "Голосовой захват",
        "குரல் பிடிப்பு", "การบันทึกเสียง", "Ses Yakalama", "Голосове захоплення",
        "صوتی کیپچر", "Ghi âm giọng nói", "语音采集", "語音擷取",
    ),
    "Capture on Watch. Syncs to iPhone.": values(
        "سجّل على Watch. تتم المزامنة مع iPhone.",
        "Watch-এ রেকর্ড করুন। iPhone-এর সঙ্গে সিঙ্ক হবে।",
        "Auf der Watch aufnehmen. Wird mit dem iPhone synchronisiert.",
        "Captura en el Watch. Se sincroniza con el iPhone.",
        "Enregistrez sur la Watch. Synchronisation avec l’iPhone.",
        "Watch पर रिकॉर्ड करें। iPhone से सिंक होता है।",
        "Rekam di Watch. Disinkronkan ke iPhone.",
        "Registra su Watch. Si sincronizza con iPhone.",
        "Watchで録音。iPhoneに同期します。",
        "Watch에서 녹음하고 iPhone과 동기화합니다.",
        "Neem op met Watch. Synchroniseert met iPhone.",
        "Nagrywaj na Watch. Synchronizuje się z iPhone.",
        "Grave no Watch. Sincroniza com o iPhone.",
        "Записывайте на Watch. Синхронизируется с iPhone.",
        "Watch-இல் பதிவு செய்யுங்கள். iPhone உடன் ஒத்திசைக்கப்படும்.",
        "บันทึกบน Watch แล้วซิงค์กับ iPhone",
        "Watch’ta kaydedin. iPhone ile eşzamanlanır.",
        "Записуйте на Watch. Синхронізується з iPhone.",
        "Watch پر ریکارڈ کریں۔ iPhone کے ساتھ مطابقت پذیر ہوتا ہے۔",
        "Ghi âm trên Watch. Đồng bộ với iPhone.",
        "在 Watch 上录音，并同步到 iPhone。",
        "在 Watch 上錄音，並同步到 iPhone。",
    ),
    "Saved on iPhone": values(
        "تم الحفظ على iPhone", "iPhone-এ সংরক্ষিত", "Auf dem iPhone gespeichert",
        "Guardado en el iPhone", "Enregistré sur l’iPhone", "iPhone पर सहेजा गया",
        "Disimpan di iPhone", "Salvato su iPhone", "iPhoneに保存済み", "iPhone에 저장됨",
        "Op iPhone bewaard", "Zapisano na iPhone", "Salvo no iPhone", "Сохранено на iPhone",
        "iPhone-இல் சேமிக்கப்பட்டது", "บันทึกบน iPhone แล้ว", "iPhone’a kaydedildi",
        "Збережено на iPhone", "iPhone پر محفوظ ہو گیا", "Đã lưu trên iPhone",
        "已存储到 iPhone", "已儲存至 iPhone",
    ),
    "Delivered successfully. You can record another.": values(
        "تم التسليم بنجاح. يمكنك بدء تسجيل جديد.",
        "সফলভাবে পৌঁছেছে। আপনি আরেকটি রেকর্ডিং করতে পারেন।",
        "Erfolgreich übertragen. Du kannst eine weitere Aufnahme starten.",
        "Entregado correctamente. Puedes hacer otra grabación.",
        "Transmis avec succès. Vous pouvez effectuer un autre enregistrement.",
        "सफलतापूर्वक भेज दिया गया। आप एक और रिकॉर्डिंग कर सकते हैं।",
        "Berhasil dikirim. Anda dapat merekam lagi.",
        "Trasferito correttamente. Puoi effettuare un’altra registrazione.",
        "正常に転送されました。続けて録音できます。",
        "성공적으로 전송되었습니다. 다시 녹음할 수 있습니다.",
        "Succesvol afgeleverd. Je kunt nog een opname maken.",
        "Przesłano pomyślnie. Możesz rozpocząć kolejne nagranie.",
        "Enviado com sucesso. Você pode fazer outra gravação.",
        "Успешно передано. Можно начать новую запись.",
        "வெற்றிகரமாக அனுப்பப்பட்டது. மேலும் ஒரு பதிவைத் தொடங்கலாம்.",
        "ส่งเรียบร้อยแล้ว คุณสามารถบันทึกอีกครั้งได้",
        "Başarıyla aktarıldı. Yeni bir kayıt yapabilirsiniz.",
        "Успішно передано. Можна почати новий запис.",
        "کامیابی سے پہنچا دیا گیا۔ آپ ایک اور ریکارڈنگ کر سکتے ہیں۔",
        "Đã chuyển thành công. Bạn có thể ghi âm lần nữa.",
        "传送成功。你可以继续录音。",
        "傳送成功。你可以繼續錄音。",
    ),
    "Pause • Stop • Cancel": values(
        "إيقاف مؤقت • إيقاف • إلغاء", "বিরতি • থামান • বাতিল", "Pause • Stoppen • Abbrechen",
        "Pausar • Detener • Cancelar", "Pause • Arrêter • Annuler", "विराम • रोकें • रद्द करें",
        "Jeda • Hentikan • Batal", "Pausa • Interrompi • Annulla", "一時停止 • 停止 • キャンセル",
        "일시 정지 • 중지 • 취소", "Pauze • Stoppen • Annuleren", "Wstrzymaj • Zatrzymaj • Anuluj",
        "Pausar • Parar • Cancelar", "Пауза • Остановить • Отменить",
        "இடைநிறுத்து • நிறுத்து • ரத்துசெய்", "พัก • หยุด • ยกเลิก",
        "Duraklat • Durdur • İptal", "Пауза • Зупинити • Скасувати",
        "موقوف کریں • روکیں • منسوخ کریں", "Tạm dừng • Dừng • Hủy",
        "暂停 • 停止 • 取消", "暫停 • 停止 • 取消",
    ),
    "Resume • Stop • Cancel": values(
        "استئناف • إيقاف • إلغاء", "চালিয়ে যান • থামান • বাতিল",
        "Fortsetzen • Stoppen • Abbrechen", "Reanudar • Detener • Cancelar",
        "Reprendre • Arrêter • Annuler", "फिर शुरू करें • रोकें • रद्द करें",
        "Lanjutkan • Hentikan • Batal", "Riprendi • Interrompi • Annulla",
        "再開 • 停止 • キャンセル", "재개 • 중지 • 취소", "Hervatten • Stoppen • Annuleren",
        "Wznów • Zatrzymaj • Anuluj", "Retomar • Parar • Cancelar",
        "Продолжить • Остановить • Отменить", "தொடர்க • நிறுத்து • ரத்துசெய்",
        "ทำต่อ • หยุด • ยกเลิก", "Sürdür • Durdur • İptal",
        "Продовжити • Зупинити • Скасувати", "دوبارہ شروع کریں • روکیں • منسوخ کریں",
        "Tiếp tục • Dừng • Hủy", "继续 • 停止 • 取消", "繼續 • 停止 • 取消",
    ),
    "CAPTURE PRESETS": values(
        "إعدادات الالتقاط المسبقة", "ক্যাপচার প্রিসেট", "AUFNAHMEVOREINSTELLUNGEN",
        "PREAJUSTES DE CAPTURA", "PRÉRÉGLAGES DE CAPTURE", "कैप्चर प्रीसेट",
        "PRESET TANGKAPAN", "PREIMPOSTAZIONI DI ACQUISIZIONE", "キャプチャプリセット",
        "캡처 프리셋", "VASTLEGVOORINSTELLINGEN", "USTAWIENIA PRZECHWYTYWANIA",
        "PREDEFINIÇÕES DE CAPTURA", "ПРЕДУСТАНОВКИ ЗАХВАТА", "பிடிப்பு முன்னமைவுகள்",
        "ค่าจับภาพที่ตั้งไว้", "YAKALAMA ÖN AYARLARI", "ПЕРЕДУСТАНОВКИ ЗАХОПЛЕННЯ",
        "کیپچر پری سیٹس", "CẤU HÌNH GHI NHANH", "采集预设", "擷取預設",
    ),
    "Capture Presets": values(
        "إعدادات الالتقاط المسبقة", "ক্যাপচার প্রিসেট", "Aufnahmevoreinstellungen",
        "Preajustes de captura", "Préréglages de capture", "कैप्चर प्रीसेट", "Preset Tangkapan",
        "Preimpostazioni di acquisizione", "キャプチャプリセット", "캡처 프리셋",
        "Vastlegvoorinstellingen", "Ustawienia przechwytywania", "Predefinições de captura",
        "Предустановки захвата", "பிடிப்பு முன்னமைவுகள்", "ค่าจับภาพที่ตั้งไว้",
        "Yakalama Ön Ayarları", "Передустановки захоплення", "کیپچر پری سیٹس",
        "Cấu hình ghi nhanh", "采集预设", "擷取預設",
    ),
    "Default transcription": values(
        "النسخ الافتراضي", "ডিফল্ট ট্রান্সক্রিপশন", "Standardtranskription",
        "Transcripción predeterminada", "Transcription par défaut", "डिफ़ॉल्ट ट्रांसक्रिप्शन",
        "Transkripsi bawaan", "Trascrizione predefinita", "デフォルトの文字起こし", "기본 전사",
        "Standaardtranscriptie", "Domyślna transkrypcja", "Transcrição padrão",
        "Транскрипция по умолчанию", "இயல்புநிலை உரைமாற்றம்", "การถอดเสียงเริ่มต้น",
        "Varsayılan transkripsiyon", "Типова транскрипція", "ڈیفالٹ ٹرانسکرپشن",
        "Bản chép lời mặc định", "默认转录", "預設轉錄",
    ),
    "Download Model": values(
        "تنزيل النموذج", "মডেল ডাউনলোড করুন", "Modell laden", "Descargar modelo",
        "Télécharger le modèle", "मॉडल डाउनलोड करें", "Unduh Model", "Scarica modello",
        "モデルをダウンロード", "모델 다운로드", "Model downloaden", "Pobierz model",
        "Baixar modelo", "Скачать модель", "மாதிரியைப் பதிவிறக்கு", "ดาวน์โหลดโมเดล",
        "Modeli İndir", "Завантажити модель", "ماڈل ڈاؤن لوڈ کریں", "Tải mô hình xuống",
        "下载模型", "下載模型",
    ),
    "Feedback": values(
        "الملاحظات", "মতামত", "Feedback", "Comentarios", "Commentaires", "प्रतिक्रिया",
        "Masukan", "Feedback", "フィードバック", "피드백", "Feedback", "Opinie", "Feedback",
        "Обратная связь", "கருத்து", "ความคิดเห็น", "Geri Bildirim", "Зворотний зв’язок",
        "رائے", "Phản hồi", "反馈", "意見回饋",
    ),
    "Default for Capture": values(
        "الإعداد الافتراضي للالتقاط", "ক্যাপচারের ডিফল্ট", "Standard für Erfassung",
        "Predeterminado para Captura", "Par défaut pour la capture", "कैप्चर के लिए डिफ़ॉल्ट",
        "Bawaan untuk Tangkapan", "Predefinito per Acquisizione", "キャプチャのデフォルト",
        "캡처 기본값", "Standaard voor vastleggen", "Domyślne dla przechwytywania",
        "Padrão para Captura", "По умолчанию для захвата", "பிடிப்பிற்கான இயல்புநிலை",
        "ค่าเริ่มต้นสำหรับการจับภาพ", "Yakalama için Varsayılan", "Типово для захоплення",
        "کیپچر کے لیے ڈیفالٹ", "Mặc định cho Ghi nhanh", "采集默认项", "擷取預設",
    ),
    "Capture Processing": values(
        "معالجة الالتقاط", "ক্যাপচার প্রক্রিয়াকরণ", "Erfassungsverarbeitung",
        "Procesamiento de captura", "Traitement de la capture", "कैप्चर प्रोसेसिंग",
        "Pemrosesan Tangkapan", "Elaborazione acquisizione", "キャプチャ処理", "캡처 처리",
        "Verwerking van vastlegging", "Przetwarzanie przechwytywania",
        "Processamento de captura", "Обработка захвата", "பிடிப்பு செயலாக்கம்",
        "การประมวลผลการจับภาพ", "Yakalama İşleme", "Обробка захоплення",
        "کیپچر پروسیسنگ", "Xử lý nội dung ghi nhanh", "采集处理", "擷取處理",
    ),
    "Live transcript · sending immediately": values(
        "نسخ مباشر · إرسال فوري", "লাইভ ট্রান্সক্রিপ্ট · সঙ্গে সঙ্গে পাঠানো হচ্ছে",
        "Live-Transkript · wird sofort gesendet", "Transcripción en directo · envío inmediato",
        "Transcription en direct · envoi immédiat", "लाइव ट्रांसक्रिप्ट · तुरंत भेजा जा रहा है",
        "Transkrip langsung · langsung dikirim", "Trascrizione in diretta · invio immediato",
        "リアルタイム文字起こし · すぐに送信", "실시간 전사 · 즉시 전송",
        "Live-transcript · direct verzenden", "Transkrypcja na żywo · wysyłanie natychmiast",
        "Transcrição ao vivo · envio imediato", "Транскрипция в реальном времени · немедленная отправка",
        "நேரலை உரைமாற்றம் · உடனடியாக அனுப்பப்படுகிறது", "ถอดเสียงสด · ส่งทันที",
        "Canlı transkripsiyon · hemen gönderiliyor", "Транскрипція наживо · негайне надсилання",
        "لائیو ٹرانسکرپٹ · فوراً بھیجا جا رہا ہے", "Chép lời trực tiếp · gửi ngay",
        "实时转录 · 立即发送", "即時轉錄 · 立即傳送",
    ),
    "Composer remains available while you record": values(
        "يظل محرر النص متاحًا أثناء التسجيل", "রেকর্ড করার সময়ও এডিটর ব্যবহার করা যাবে",
        "Der Editor bleibt während der Aufnahme verfügbar", "El editor sigue disponible mientras grabas",
        "L’éditeur reste disponible pendant l’enregistrement", "रिकॉर्डिंग के दौरान भी एडिटर उपलब्ध रहता है",
        "Editor tetap tersedia saat Anda merekam", "L’editor resta disponibile durante la registrazione",
        "録音中もエディタを使用できます", "녹음 중에도 편집기를 사용할 수 있습니다",
        "De editor blijft beschikbaar tijdens de opname", "Edytor pozostaje dostępny podczas nagrywania",
        "O editor continua disponível durante a gravação", "Редактор остаётся доступным во время записи",
        "பதிவு செய்யும்போதும் திருத்தி கிடைக்கும்", "คุณยังใช้ตัวแก้ไขได้ขณะบันทึก",
        "Kayıt sırasında düzenleyiciyi kullanmaya devam edebilirsiniz",
        "Редактор залишається доступним під час запису", "ریکارڈنگ کے دوران بھی ایڈیٹر دستیاب رہتا ہے",
        "Trình soạn thảo vẫn dùng được khi bạn đang ghi âm", "录音时仍可使用编辑器",
        "錄音時仍可使用編輯器",
    ),
    "Capture ideas as they arrive.": values(
        "التقط الأفكار فور ورودها.", "ভাবনা আসার সঙ্গে সঙ্গে ক্যাপচার করুন।",
        "Halte Ideen fest, sobald sie entstehen.", "Captura las ideas cuando surjan.",
        "Capturez vos idées dès qu’elles arrivent.", "विचार आते ही उन्हें कैप्चर करें।",
        "Tangkap ide saat muncul.", "Acquisisci le idee appena arrivano.",
        "アイデアが浮かんだらすぐに記録。", "아이디어가 떠오르는 즉시 캡처하세요.",
        "Leg ideeën vast zodra ze opkomen.", "Zapisuj pomysły, gdy tylko się pojawią.",
        "Capture ideias assim que surgirem.", "Фиксируйте идеи сразу, как только они появляются.",
        "எண்ணங்கள் தோன்றியவுடன் அவற்றைப் பிடியுங்கள்.", "จับไอเดียทันทีที่นึกออก",
        "Fikirleri ortaya çıktıkları anda yakalayın.", "Фіксуйте ідеї, щойно вони з’являються.",
        "خیالات آتے ہی کیپچر کریں۔", "Ghi lại ý tưởng ngay khi chúng xuất hiện.",
        "灵感出现时立即记录。", "靈感出現時立即記錄。",
    ),
    "Everything stays on this device.": values(
        "يبقى كل شيء على هذا الجهاز.", "সবকিছু এই ডিভাইসেই থাকে।",
        "Alles bleibt auf diesem Gerät.", "Todo permanece en este dispositivo.",
        "Tout reste sur cet appareil.", "सब कुछ इसी डिवाइस पर रहता है।",
        "Semuanya tetap di perangkat ini.", "Tutto rimane su questo dispositivo.",
        "すべてこのデバイス内に保存されます。", "모든 내용은 이 기기에만 저장됩니다.",
        "Alles blijft op dit apparaat.", "Wszystko pozostaje na tym urządzeniu.",
        "Tudo permanece neste dispositivo.", "Всё остаётся на этом устройстве.",
        "அனைத்தும் இந்தச் சாதனத்திலேயே இருக்கும்.", "ทุกอย่างอยู่บนอุปกรณ์นี้",
        "Her şey bu aygıtta kalır.", "Усе залишається на цьому пристрої.",
        "سب کچھ اسی ڈیوائس پر رہتا ہے۔", "Mọi nội dung đều được lưu trên thiết bị này.",
        "所有内容都保留在此设备上。", "所有內容都保留在此裝置上。",
    ),
    "Capture an idea, task, link, file, scan, or recording.": values(
        "التقط فكرة أو مهمة أو رابطًا أو ملفًا أو مسحًا ضوئيًا أو تسجيلًا.",
        "একটি ভাবনা, কাজ, লিংক, ফাইল, স্ক্যান বা রেকর্ডিং ক্যাপচার করুন।",
        "Erfasse eine Idee, Aufgabe, einen Link, eine Datei, einen Scan oder eine Aufnahme.",
        "Captura una idea, tarea, enlace, archivo, escaneo o grabación.",
        "Capturez une idée, une tâche, un lien, un fichier, un scan ou un enregistrement.",
        "कोई विचार, कार्य, लिंक, फ़ाइल, स्कैन या रिकॉर्डिंग कैप्चर करें।",
        "Tangkap ide, tugas, tautan, file, pindaian, atau rekaman.",
        "Acquisisci un’idea, un’attività, un link, un file, una scansione o una registrazione.",
        "アイデア、タスク、リンク、ファイル、スキャン、録音をキャプチャ。",
        "아이디어, 작업, 링크, 파일, 스캔 또는 녹음을 캡처하세요.",
        "Leg een idee, taak, link, bestand, scan of opname vast.",
        "Zapisz pomysł, zadanie, link, plik, skan lub nagranie.",
        "Capture uma ideia, tarefa, link, arquivo, digitalização ou gravação.",
        "Зафиксируйте идею, задачу, ссылку, файл, скан или запись.",
        "ஒரு எண்ணம், பணி, இணைப்பு, கோப்பு, ஸ்கேன் அல்லது பதிவைப் பிடியுங்கள்.",
        "จับไอเดีย งาน ลิงก์ ไฟล์ สแกน หรือการบันทึก",
        "Bir fikir, görev, bağlantı, dosya, tarama veya kayıt yakalayın.",
        "Зафіксуйте ідею, завдання, посилання, файл, скан або запис.",
        "کوئی خیال، کام، لنک، فائل، اسکین یا ریکارڈنگ کیپچر کریں۔",
        "Ghi lại ý tưởng, tác vụ, liên kết, tệp, bản quét hoặc bản ghi âm.",
        "采集想法、任务、链接、文件、扫描件或录音。",
        "擷取想法、任務、連結、檔案、掃描或錄音。",
    ),
    "Default": values(
        "افتراضي", "ডিফল্ট", "Standard", "Predeterminado", "Par défaut", "डिफ़ॉल्ट",
        "Bawaan", "Predefinito", "デフォルト", "기본", "Standaard", "Domyślne", "Padrão",
        "По умолчанию", "இயல்புநிலை", "ค่าเริ่มต้น", "Varsayılan", "Типове", "ڈیفالٹ",
        "Mặc định", "默认", "預設",
    ),
    "Record": values(
        "تسجيل", "রেকর্ড", "Aufnehmen", "Grabar", "Enregistrer", "रिकॉर्ड करें", "Rekam",
        "Registra", "録音", "녹음", "Opnemen", "Nagraj", "Gravar", "Записать", "பதிவு செய்",
        "บันทึก", "Kaydet", "Записати", "ریکارڈ کریں", "Ghi âm", "录音", "錄音",
    ),
    "Stop": values(
        "إيقاف", "থামান", "Stoppen", "Detener", "Arrêter", "रोकें", "Hentikan", "Interrompi",
        "停止", "중지", "Stoppen", "Zatrzymaj", "Parar", "Остановить", "நிறுத்து", "หยุด",
        "Durdur", "Зупинити", "روکیں", "Dừng", "停止", "停止",
    ),
    "Pause": values(
        "إيقاف مؤقت", "বিরতি", "Pause", "Pausar", "Pause", "विराम", "Jeda", "Pausa",
        "一時停止", "일시 정지", "Pauze", "Wstrzymaj", "Pausar", "Пауза", "இடைநிறுத்து",
        "พัก", "Duraklat", "Пауза", "موقوف کریں", "Tạm dừng", "暂停", "暫停",
    ),
    "Resume": values(
        "استئناف", "চালিয়ে যান", "Fortsetzen", "Reanudar", "Reprendre", "फिर शुरू करें",
        "Lanjutkan", "Riprendi", "再開", "재개", "Hervatten", "Wznów", "Retomar",
        "Продолжить", "தொடர்க", "ทำต่อ", "Sürdür", "Продовжити", "دوبارہ شروع کریں",
        "Tiếp tục", "继续", "繼續",
    ),
    "Cancel": values(
        "إلغاء", "বাতিল", "Abbrechen", "Cancelar", "Annuler", "रद्द करें", "Batal", "Annulla",
        "キャンセル", "취소", "Annuleren", "Anuluj", "Cancelar", "Отменить", "ரத்துசெய்",
        "ยกเลิก", "İptal", "Скасувати", "منسوخ کریں", "Hủy", "取消", "取消",
    ),
    "Saved": values(
        "تم الحفظ", "সংরক্ষিত", "Gespeichert", "Guardado", "Enregistré", "सहेजा गया",
        "Tersimpan", "Salvato", "保存済み", "저장됨", "Opgeslagen", "Zapisano", "Salvo",
        "Сохранено", "சேமிக்கப்பட்டது", "บันทึกแล้ว", "Kaydedildi", "Збережено", "محفوظ",
        "Đã lưu", "已保存", "已儲存",
    ),
    "On iPhone": values(
        "على iPhone", "iPhone-এ", "Auf dem iPhone", "En el iPhone", "Sur l’iPhone",
        "iPhone पर", "Di iPhone", "Su iPhone", "iPhone上", "iPhone에서", "Op iPhone",
        "Na iPhone", "No iPhone", "На iPhone", "iPhone-இல்", "บน iPhone", "iPhone’da",
        "На iPhone", "iPhone پر", "Trên iPhone", "在 iPhone 上", "在 iPhone 上",
    ),
    "Syncing to iPhone": values(
        "جارٍ المزامنة مع iPhone", "iPhone-এর সঙ্গে সিঙ্ক হচ্ছে", "Synchronisierung mit iPhone",
        "Sincronizando con el iPhone", "Synchronisation avec l’iPhone", "iPhone से सिंक हो रहा है",
        "Menyinkronkan ke iPhone", "Sincronizzazione con iPhone", "iPhoneに同期中",
        "iPhone과 동기화 중", "Synchroniseren met iPhone", "Synchronizowanie z iPhone",
        "Sincronizando com o iPhone", "Синхронизация с iPhone", "iPhone உடன் ஒத்திசைக்கப்படுகிறது",
        "กำลังซิงค์กับ iPhone", "iPhone ile eşzamanlanıyor", "Синхронізація з iPhone",
        "iPhone کے ساتھ مطابقت پذیر ہو رہا ہے", "Đang đồng bộ với iPhone",
        "正在同步到 iPhone", "正在同步至 iPhone",
    ),
    "Send Immediately": values(
        "إرسال فورًا", "এখনই পাঠান", "Sofort senden", "Enviar inmediatamente",
        "Envoyer immédiatement", "तुरंत भेजें", "Kirim Sekarang", "Invia subito",
        "すぐに送信", "즉시 전송", "Direct verzenden", "Wyślij natychmiast",
        "Enviar imediatamente", "Отправить сразу", "உடனடியாக அனுப்பு", "ส่งทันที",
        "Hemen Gönder", "Надіслати негайно", "فوراً بھیجیں", "Gửi ngay", "立即发送", "立即傳送",
    ),
    "Add to Draft": values(
        "إضافة إلى المسودة", "খসড়ায় যোগ করুন", "Zum Entwurf hinzufügen", "Añadir al borrador",
        "Ajouter au brouillon", "ड्राफ़्ट में जोड़ें", "Tambahkan ke Draf", "Aggiungi alla bozza",
        "下書きに追加", "초안에 추가", "Aan concept toevoegen", "Dodaj do wersji roboczej",
        "Adicionar ao rascunho", "Добавить в черновик", "வரைவில் சேர்", "เพิ่มไปยังฉบับร่าง",
        "Taslağa Ekle", "Додати до чернетки", "مسودے میں شامل کریں", "Thêm vào bản nháp",
        "添加到草稿", "加入草稿",
    ),
}

SCREENSHOT_REVIEWED_OVERRIDES.update({
    "On-Device Models": values(
        "النماذج على الجهاز", "ডিভাইসে থাকা মডেলসমূহ", "Modelle auf dem Gerät",
        "Modelos en el dispositivo", "Modèles sur l’appareil", "डिवाइस पर मॉडल",
        "Model di Perangkat", "Modelli sul dispositivo", "オンデバイスモデル",
        "온디바이스 모델", "Modellen op het apparaat", "Modele na urządzeniu",
        "Modelos no dispositivo", "Модели на устройстве", "சாதனத்திலுள்ள மாதிரிகள்",
        "โมเดลบนอุปกรณ์", "Aygıttaki Modeller", "Моделі на пристрої",
        "ڈیوائس پر موجود ماڈلز", "Mô hình trên thiết bị", "设备端模型", "裝置端模型",
    ),
    "Native": values(
        "أصلي", "নেটিভ", "Systemintern", "Nativo", "Natif", "नेटिव", "Bawaan sistem",
        "Nativo", "標準", "기본", "Systeemeigen", "Natywny", "Nativo", "Системный",
        "இயல்பு", "ระบบ", "Yerel", "Системний", "مقامی", "Gốc", "系统原生", "系統原生",
    ),
    "Selected": values(
        "محدد", "নির্বাচিত", "Ausgewählt", "Seleccionado", "Sélectionné", "चयनित", "Dipilih",
        "Selezionato", "選択中", "선택됨", "Geselecteerd", "Wybrano", "Selecionado",
        "Выбрано", "தேர்ந்தெடுக்கப்பட்டது", "เลือกแล้ว", "Seçildi", "Вибрано", "منتخب",
        "Đã chọn", "已选择", "已選取",
    ),
    "Download Auto-Stop": values(
        "تنزيل الإيقاف التلقائي", "স্বয়ংক্রিয় থামানো ডাউনলোড করুন",
        "Automatischen Stopp laden", "Descargar detención automática",
        "Télécharger l’arrêt automatique", "ऑटो-स्टॉप डाउनलोड करें",
        "Unduh Penghenti Otomatis", "Scarica arresto automatico", "自動停止をダウンロード",
        "자동 중지 다운로드", "Automatisch stoppen downloaden",
        "Pobierz automatyczne zatrzymywanie", "Baixar parada automática",
        "Скачать автоостановку", "தானியங்கி நிறுத்தத்தைப் பதிவிறக்கு",
        "ดาวน์โหลดการหยุดอัตโนมัติ", "Otomatik Durdurmayı İndir",
        "Завантажити автозупинку", "خودکار توقف ڈاؤن لوڈ کریں",
        "Tải tính năng tự động dừng", "下载自动停止", "下載自動停止",
    ),
    "Unlock Unlimited": values(
        "فتح الاستخدام غير المحدود", "আনলিমিটেড ব্যবহার চালু করুন",
        "Unbegrenzte Nutzung freischalten", "Desbloquear uso ilimitado",
        "Débloquer l’utilisation illimitée", "अनलिमिटेड उपयोग अनलॉक करें",
        "Buka Penggunaan Tanpa Batas", "Sblocca l’uso illimitato", "無制限利用を解除",
        "무제한 이용 잠금 해제", "Onbeperkt gebruik ontgrendelen", "Odblokuj bez limitu",
        "Desbloquear uso ilimitado", "Разблокировать безлимитный доступ",
        "வரம்பற்ற பயன்பாட்டைத் திற", "ปลดล็อกการใช้งานไม่จำกัด",
        "Sınırsız Kullanımın Kilidini Aç", "Розблокувати безлімітний доступ",
        "لامحدود استعمال کھولیں", "Mở khóa sử dụng không giới hạn",
        "解锁无限使用", "解鎖無限使用",
    ),
    "View Lifetime Options": values(
        "عرض خيارات الشراء مدى الحياة", "আজীবন ব্যবহারের বিকল্প দেখুন",
        "Optionen für lebenslange Nutzung", "Ver opciones de acceso de por vida",
        "Voir les options d’accès à vie", "लाइफ़टाइम विकल्प देखें",
        "Lihat Opsi Akses Seumur Hidup", "Visualizza opzioni a vita", "買い切りオプションを表示",
        "평생 이용 옵션 보기", "Opties voor levenslange toegang",
        "Zobacz opcje dożywotniego dostępu", "Ver opções de acesso vitalício",
        "Варианты пожизненного доступа", "வாழ்நாள் அணுகல் விருப்பங்களைக் காண்க",
        "ดูตัวเลือกสิทธิ์ใช้งานตลอดชีพ", "Ömür Boyu Erişim Seçenekleri",
        "Варіанти довічного доступу", "تاحیات رسائی کے اختیارات دیکھیں",
        "Xem tùy chọn truy cập trọn đời", "查看终身使用选项", "查看終身使用選項",
    ),
    "Customization": values(
        "التخصيص", "কাস্টমাইজেশন", "Anpassung", "Personalización", "Personnalisation",
        "अनुकूलन", "Penyesuaian", "Personalizzazione", "カスタマイズ", "사용자 설정",
        "Aanpassing", "Dostosowanie", "Personalização", "Настройка", "தனிப்பயனாக்கம்",
        "การปรับแต่ง", "Özelleştirme", "Налаштування", "حسب ضرورت", "Tùy chỉnh",
        "自定义", "自訂",
    ),
    "Stats": values(
        "الإحصاءات", "পরিসংখ্যান", "Statistiken", "Estadísticas", "Statistiques", "आँकड़े",
        "Statistik", "Statistiche", "統計", "통계", "Statistieken", "Statystyki",
        "Estatísticas", "Статистика", "புள்ளிவிவரங்கள்", "สถิติ", "İstatistikler",
        "Статистика", "اعداد و شمار", "Thống kê", "统计", "統計",
    ),
    "Keyboard": values(
        "لوحة المفاتيح", "কীবোর্ড", "Tastatur", "Teclado", "Clavier", "कीबोर्ड",
        "Papan Ketik", "Tastiera", "キーボード", "키보드", "Toetsenbord", "Klawiatura",
        "Teclado", "Клавиатура", "விசைப்பலகை", "แป้นพิมพ์", "Klavye", "Клавіатура",
        "کی بورڈ", "Bàn phím", "键盘", "鍵盤",
    ),
    "Capture Bar": values(
        "شريط الالتقاط", "ক্যাপচার বার", "Erfassungsleiste", "Barra de captura",
        "Barre de capture", "कैप्चर बार", "Bilah Tangkapan", "Barra di acquisizione",
        "キャプチャバー", "캡처 바", "Vastlegbalk", "Pasek przechwytywania",
        "Barra de captura", "Панель захвата", "பிடிப்பு பட்டை", "แถบจับภาพ",
        "Yakalama Çubuğu", "Панель захоплення", "کیپچر بار", "Thanh ghi nhanh",
        "采集栏", "擷取列",
    ),
    "Haptic Feedback": values(
        "ردود الفعل اللمسية", "হ্যাপটিক প্রতিক্রিয়া", "Haptisches Feedback",
        "Respuesta háptica", "Retour haptique", "हैप्टिक फ़ीडबैक", "Umpan Balik Haptik",
        "Feedback aptico", "触覚フィードバック", "햅틱 피드백", "Haptische feedback",
        "Reakcje haptyczne", "Retorno tátil", "Тактильный отклик",
        "தொட்டு உணரும் பின்னூட்டம்", "การตอบสนองแบบสั่น", "Dokunsal Geri Bildirim",
        "Тактильний відгук", "ہیپٹک فیڈ بیک", "Phản hồi xúc giác", "触觉反馈", "觸覺回饋",
    ),
    "Live Activity Monitor": values(
        "مراقب النشاط المباشر", "লাইভ অ্যাক্টিভিটি মনিটর", "Live-Aktivitätsanzeige",
        "Monitor de actividad en directo", "Suivi des activités en direct",
        "लाइव एक्टिविटी मॉनिटर", "Monitor Aktivitas Langsung",
        "Monitor attività in tempo reale", "ライブアクティビティモニタ", "실시간 현황 모니터",
        "Live-activiteitenmonitor", "Monitor aktywności na żywo",
        "Monitor de atividade ao vivo", "Монитор текущей активности",
        "நேரலை செயல்பாட்டு கண்காணிப்பு", "ตัวตรวจสอบกิจกรรมสด",
        "Canlı Etkinlik İzleyicisi", "Монітор поточної активності",
        "لائیو ایکٹیویٹی مانیٹر", "Trình theo dõi hoạt động trực tiếp",
        "实时活动监控", "即時動態監控",
    ),
    "Lock Screen Record Button": values(
        "زر التسجيل على شاشة القفل", "লক স্ক্রিন রেকর্ড বোতাম",
        "Aufnahmetaste auf dem Sperrbildschirm", "Botón de grabación en la pantalla bloqueada",
        "Bouton d’enregistrement sur l’écran verrouillé", "लॉक स्क्रीन रिकॉर्ड बटन",
        "Tombol Rekam di Layar Terkunci", "Pulsante di registrazione sulla schermata di blocco",
        "ロック画面の録音ボタン", "잠금 화면 녹음 버튼",
        "Opnameknop op vergrendelscherm", "Przycisk nagrywania na ekranie blokady",
        "Botão de gravação na tela bloqueada", "Кнопка записи на экране блокировки",
        "பூட்டுத் திரை பதிவு பொத்தான்", "ปุ่มบันทึกบนหน้าจอล็อก",
        "Kilit Ekranı Kayıt Düğmesi", "Кнопка запису на екрані блокування",
        "لاک اسکرین ریکارڈ بٹن", "Nút ghi âm trên màn hình khóa",
        "锁定屏幕录音按钮", "鎖定畫面錄音按鈕",
    ),
    "What is a Capture Preset?": values(
        "ما الإعداد المسبق للالتقاط؟", "ক্যাপচার প্রিসেট কী?",
        "Was ist eine Aufnahmevoreinstellung?", "¿Qué es un preajuste de captura?",
        "Qu’est-ce qu’un préréglage de capture ?", "कैप्चर प्रीसेट क्या है?",
        "Apa itu Preset Tangkapan?", "Che cos’è una preimpostazione di acquisizione?",
        "キャプチャプリセットとは？", "캡처 프리셋이란?", "Wat is een vastlegvoorinstelling?",
        "Czym jest ustawienie przechwytywania?", "O que é uma predefinição de captura?",
        "Что такое предустановка захвата?", "பிடிப்பு முன்னமைவு என்றால் என்ன?",
        "ค่าจับภาพที่ตั้งไว้คืออะไร", "Yakalama Ön Ayarı Nedir?",
        "Що таке передустановка захоплення?", "کیپچر پری سیٹ کیا ہے؟",
        "Cấu hình ghi nhanh là gì?", "什么是采集预设？", "什麼是擷取預設？",
    ),
    "Add Preset": values(
        "إضافة إعداد مسبق", "প্রিসেট যোগ করুন", "Voreinstellung hinzufügen",
        "Añadir preajuste", "Ajouter un préréglage", "प्रीसेट जोड़ें", "Tambah Preset",
        "Aggiungi preimpostazione", "プリセットを追加", "프리셋 추가",
        "Voorinstelling toevoegen", "Dodaj ustawienie", "Adicionar predefinição",
        "Добавить предустановку", "முன்னமைவைச் சேர்", "เพิ่มค่าที่ตั้งไว้",
        "Ön Ayar Ekle", "Додати передустановку", "پری سیٹ شامل کریں", "Thêm cấu hình",
        "添加预设", "新增預設",
    ),
    "Shared Formatting": values(
        "تنسيق مشترك", "শেয়ার করা ফরম্যাটিং", "Gemeinsame Formatierung",
        "Formato compartido", "Mise en forme partagée", "साझा फ़ॉर्मैटिंग",
        "Pemformatan Bersama", "Formattazione condivisa", "共通フォーマット", "공유 서식",
        "Gedeelde opmaak", "Wspólne formatowanie", "Formatação compartilhada",
        "Общее форматирование", "பகிரப்பட்ட வடிவமைப்பு", "การจัดรูปแบบร่วมกัน",
        "Paylaşılan Biçimlendirme", "Спільне форматування", "مشترکہ فارمیٹنگ",
        "Định dạng dùng chung", "共享格式", "共用格式",
    ),
    "Entry Templates": values(
        "قوالب الإدخال", "এন্ট্রি টেমপ্লেট", "Eintragsvorlagen", "Plantillas de entrada",
        "Modèles d’entrée", "एंट्री टेम्प्लेट", "Templat Entri", "Modelli per le voci",
        "エントリテンプレート", "항목 템플릿", "Invoersjablonen", "Szablony wpisów",
        "Modelos de entrada", "Шаблоны записей", "பதிவு வார்ப்புருக்கள்",
        "เทมเพลตรายการ", "Girdi Şablonları", "Шаблони записів", "اندراج ٹیمپلیٹس",
        "Mẫu mục nhập", "条目模板", "項目範本",
    ),
    "Identity": values(
        "الهوية", "পরিচয়", "Identität", "Identidad", "Identité", "पहचान", "Identitas",
        "Identità", "基本情報", "기본 정보", "Identiteit", "Tożsamość", "Identidade",
        "Основные сведения", "அடையாளம்", "ข้อมูลพื้นฐาน", "Kimlik", "Основні відомості",
        "شناخت", "Thông tin cơ bản", "基本信息", "基本資訊",
    ),
    "Icon": values(
        "الأيقونة", "আইকন", "Symbol", "Icono", "Icône", "आइकन", "Ikon", "Icona",
        "アイコン", "아이콘", "Pictogram", "Ikona", "Ícone", "Значок", "படவுரு", "ไอคอน",
        "Simge", "Значок", "آئیکن", "Biểu tượng", "图标", "圖示",
    ),
    "Enabled": values(
        "مفعّل", "সক্রিয়", "Aktiviert", "Activado", "Activé", "चालू", "Aktif", "Attivo",
        "有効", "활성화", "Ingeschakeld", "Włączone", "Ativado", "Включено",
        "இயக்கப்பட்டது", "เปิดใช้งาน", "Etkin", "Увімкнено", "فعال", "Đã bật",
        "已启用", "已啟用",
    ),
    "Use as Capture Default": values(
        "استخدام كإعداد افتراضي للالتقاط", "ক্যাপচারের ডিফল্ট হিসেবে ব্যবহার করুন",
        "Als Standard für Erfassung verwenden", "Usar como valor predeterminado de Captura",
        "Utiliser par défaut pour la capture", "कैप्चर के डिफ़ॉल्ट के रूप में उपयोग करें",
        "Gunakan sebagai Bawaan Tangkapan", "Usa come predefinito per Acquisizione",
        "キャプチャのデフォルトに設定", "캡처 기본값으로 사용", "Als standaard voor vastleggen gebruiken",
        "Użyj jako domyślnego dla przechwytywania", "Usar como padrão para Captura",
        "Использовать по умолчанию для захвата", "பிடிப்பிற்கான இயல்புநிலையாகப் பயன்படுத்து",
        "ใช้เป็นค่าเริ่มต้นสำหรับการจับภาพ", "Yakalama için Varsayılan Olarak Kullan",
        "Використовувати типово для захоплення", "کیپچر کے ڈیفالٹ کے طور پر استعمال کریں",
        "Dùng làm mặc định cho Ghi nhanh", "设为采集默认项", "設為擷取預設",
    ),
    "Mode": values(
        "الوضع", "মোড", "Modus", "Modo", "Mode", "मोड", "Mode", "Modalità", "モード",
        "모드", "Modus", "Tryb", "Modo", "Режим", "பயன்முறை", "โหมด", "Mod",
        "Режим", "موڈ", "Chế độ", "模式", "模式",
    ),
    "Destination": values(
        "الوجهة", "গন্তব্য", "Ziel", "Destino", "Destination", "गंतव्य", "Tujuan",
        "Destinazione", "保存先", "대상", "Bestemming", "Miejsce docelowe", "Destino",
        "Место назначения", "இலக்கு", "ปลายทาง", "Hedef", "Місце призначення",
        "منزل", "Đích", "目标位置", "目的地",
    ),
    "Legacy Voice File Export": values(
        "تصدير ملفات الصوت القديمة", "পুরোনো ভয়েস ফাইল এক্সপোর্ট",
        "Export älterer Sprachdateien", "Exportación de archivos de voz heredada",
        "Export des anciens fichiers vocaux", "पुराने वॉइस फ़ाइलों का निर्यात",
        "Ekspor File Suara Lama", "Esportazione file vocali precedente",
        "従来の音声ファイル書き出し", "기존 음성 파일 내보내기",
        "Export van oudere spraakbestanden", "Eksport starszych plików głosowych",
        "Exportação de arquivos de voz legados", "Экспорт старых голосовых файлов",
        "பழைய குரல் கோப்பு ஏற்றுமதி", "การส่งออกไฟล์เสียงแบบเดิม",
        "Eski Ses Dosyası Dışa Aktarımı", "Експорт старих голосових файлів",
        "پرانی صوتی فائلوں کی برآمد", "Xuất tệp giọng nói kiểu cũ",
        "旧版语音文件导出", "舊版語音檔案匯出",
    ),
    "Export Directory": values(
        "مجلد التصدير", "এক্সপোর্ট ফোল্ডার", "Exportordner", "Carpeta de exportación",
        "Dossier d’exportation", "एक्सपोर्ट फ़ोल्डर", "Folder Ekspor", "Cartella di esportazione",
        "書き出しフォルダ", "내보내기 폴더", "Exportmap", "Folder eksportu",
        "Pasta de exportação", "Папка экспорта", "ஏற்றுமதி கோப்புறை", "โฟลเดอร์ส่งออก",
        "Dışa Aktarma Klasörü", "Папка експорту", "برآمدی فولڈر", "Thư mục xuất",
        "导出文件夹", "匯出資料夾",
    ),
    "Settings": values(
        "الإعدادات", "সেটিংস", "Einstellungen", "Ajustes", "Réglages", "सेटिंग्स", "Pengaturan",
        "Impostazioni", "設定", "설정", "Instellingen", "Ustawienia", "Ajustes", "Настройки",
        "அமைப்புகள்", "การตั้งค่า", "Ayarlar", "Налаштування", "ترتیبات", "Cài đặt",
        "设置", "設定",
    ),
    "Name": values(
        "الاسم", "নাম", "Name", "Nombre", "Nom", "नाम", "Nama", "Nome", "名前", "이름",
        "Naam", "Nazwa", "Nome", "Название", "பெயர்", "ชื่อ", "Ad", "Назва", "نام", "Tên",
        "名称", "名稱",
    ),
    "Format": values(
        "التنسيق", "ফরম্যাট", "Format", "Formato", "Format", "फ़ॉर्मैट", "Format", "Formato",
        "形式", "형식", "Indeling", "Format", "Formato", "Формат", "வடிவம்", "รูปแบบ",
        "Biçim", "Формат", "فارمیٹ", "Định dạng", "格式", "格式",
    ),
    "Save Notes to Files": values(
        "حفظ الملاحظات في ملفات", "নোট ফাইলে সংরক্ষণ করুন", "Notizen in Dateien speichern",
        "Guardar notas en archivos", "Enregistrer les notes dans des fichiers",
        "नोट्स को फ़ाइलों में सहेजें", "Simpan Catatan ke File", "Salva le note nei file",
        "メモをファイルに保存", "메모를 파일에 저장", "Notities in bestanden bewaren",
        "Zapisuj notatki w plikach", "Salvar notas em arquivos", "Сохранять заметки в файлы",
        "குறிப்புகளைக் கோப்புகளில் சேமி", "บันทึกโน้ตลงในไฟล์", "Notları Dosyalara Kaydet",
        "Зберігати нотатки у файлах", "نوٹس کو فائلوں میں محفوظ کریں",
        "Lưu ghi chú vào tệp", "将笔记保存到文件", "將筆記儲存至檔案",
    ),
    "Set Up Destination…": values(
        "إعداد الوجهة…", "গন্তব্য সেট আপ করুন…", "Ziel einrichten…", "Configurar destino…",
        "Configurer la destination…", "डेस्टिनेशन सेट अप करें…", "Siapkan Tujuan…",
        "Configura destinazione…", "保存先を設定…", "대상 설정…", "Bestemming instellen…",
        "Skonfiguruj miejsce docelowe…", "Configurar destino…", "Настроить место назначения…",
        "இலக்கை அமை…", "ตั้งค่าปลายทาง…", "Hedefi Ayarla…",
        "Налаштувати місце призначення…", "منزل سیٹ اپ کریں…", "Thiết lập đích…",
        "设置目标位置…", "設定目的地…",
    ),
})

SCREENSHOT_REVIEWED_OVERRIDES.update({
    "Vibrate on key press. Requires Allow Full Access.": values(
        "اهتز عند الضغط على مفتاح. يتطلب السماح بالوصول الكامل.",
        "কী চাপলে কম্পন দিন। সম্পূর্ণ অ্যাক্সেসের অনুমতি প্রয়োজন।",
        "Bei Tastendruck vibrieren. Erfordert „Vollen Zugriff erlauben“.",
        "Vibra al pulsar una tecla. Requiere permitir acceso total.",
        "Vibre à chaque appui. Nécessite l’autorisation d’accès complet.",
        "कुंजी दबाने पर कंपन करें। पूर्ण एक्सेस की अनुमति आवश्यक है।",
        "Bergetar saat tombol ditekan. Memerlukan Izinkan Akses Penuh.",
        "Vibra alla pressione dei tasti. Richiede Consenti accesso completo.",
        "キーを押したときに振動します。「フルアクセスを許可」が必要です。",
        "키를 누를 때 진동합니다. 전체 접근 허용이 필요합니다.",
        "Tril bij een toetsaanslag. Vereist Sta volledige toegang toe.",
        "Wibruj przy naciśnięciu klawisza. Wymaga pełnego dostępu.",
        "Vibra ao pressionar teclas. Requer Permitir Acesso Total.",
        "Вибрация при нажатии клавиш. Требуется полный доступ.",
        "விசையை அழுத்தும்போது அதிரும். முழு அணுகலை அனுமதிக்க வேண்டும்.",
        "สั่นเมื่อกดปุ่ม ต้องอนุญาตการเข้าถึงแบบเต็ม",
        "Tuşa basıldığında titreşir. Tam Erişime İzin Verilmesi gerekir.",
        "Вібрація під час натискання клавіш. Потрібен повний доступ.",
        "کلید دبانے پر وائبریٹ کریں۔ مکمل رسائی کی اجازت درکار ہے۔",
        "Rung khi nhấn phím. Cần cho phép Truy cập đầy đủ.",
        "按键时振动。需要允许完全访问。", "按鍵時震動。需要允許完整取用權限。",
    ),
    "Show Vox.md status and Record/Stop controls on the Lock Screen and Dynamic Island while listening.": values(
        "اعرض حالة Vox.md وأزرار التسجيل والإيقاف على شاشة القفل وDynamic Island أثناء الاستماع.",
        "শোনার সময় লক স্ক্রিন ও Dynamic Island-এ Vox.md-এর অবস্থা এবং রেকর্ড/থামান নিয়ন্ত্রণ দেখান।",
        "Zeigt beim Zuhören Vox.md-Status und Aufnahme/Stopp-Steuerung auf Sperrbildschirm und Dynamic Island.",
        "Muestra el estado de Vox.md y los controles Grabar/Detener en la pantalla bloqueada y Dynamic Island mientras escucha.",
        "Affiche l’état de Vox.md et les commandes Enregistrer/Arrêter sur l’écran verrouillé et Dynamic Island pendant l’écoute.",
        "सुनते समय लॉक स्क्रीन और Dynamic Island पर Vox.md की स्थिति और रिकॉर्ड/रोकें कंट्रोल दिखाएँ।",
        "Tampilkan status Vox.md dan kontrol Rekam/Hentikan di Layar Terkunci dan Dynamic Island saat mendengarkan.",
        "Mostra lo stato di Vox.md e i controlli Registra/Interrompi sulla schermata di blocco e Dynamic Island durante l’ascolto.",
        "聞き取り中、ロック画面とDynamic IslandにVox.mdの状態と録音／停止コントロールを表示します。",
        "듣는 동안 잠금 화면과 Dynamic Island에 Vox.md 상태 및 녹음/중지 제어를 표시합니다.",
        "Toon tijdens het luisteren de Vox.md-status en knoppen voor Opnemen/Stoppen op vergrendelscherm en Dynamic Island.",
        "Podczas nasłuchiwania pokazuj stan Vox.md oraz przyciski Nagraj/Zatrzymaj na ekranie blokady i Dynamic Island.",
        "Exibe o status do Vox.md e controles Gravar/Parar na tela bloqueada e Dynamic Island durante a escuta.",
        "Показывать состояние Vox.md и кнопки записи/остановки на экране блокировки и Dynamic Island во время прослушивания.",
        "கேட்கும்போது பூட்டுத் திரை மற்றும் Dynamic Island-இல் Vox.md நிலை மற்றும் பதிவு/நிறுத்து கட்டுப்பாடுகளைக் காட்டு.",
        "แสดงสถานะ Vox.md และปุ่มบันทึก/หยุดบนหน้าจอล็อกและ Dynamic Island ขณะฟัง",
        "Dinlerken kilit ekranı ve Dynamic Island’da Vox.md durumunu ve Kaydet/Durdur denetimlerini gösterir.",
        "Показувати стан Vox.md і кнопки запису/зупинки на екрані блокування та Dynamic Island під час прослуховування.",
        "سنتے وقت لاک اسکرین اور Dynamic Island پر Vox.md کی حالت اور ریکارڈ/روکنے کے کنٹرول دکھائیں۔",
        "Hiển thị trạng thái Vox.md và nút Ghi/Dừng trên màn hình khóa và Dynamic Island khi đang nghe.",
        "监听时在锁定屏幕和灵动岛显示 Vox.md 状态及录音/停止控制。",
        "聆聽時在鎖定畫面與動態島顯示 Vox.md 狀態和錄音/停止控制。",
    ),
    "Allow the Quick Record widget/control to open Vox.md and immediately start recording.": values(
        "اسمح لأداة التسجيل السريع بفتح Vox.md وبدء التسجيل فورًا.",
        "দ্রুত রেকর্ড উইজেটকে Vox.md খুলে সঙ্গে সঙ্গে রেকর্ডিং শুরু করতে দিন।",
        "Erlaube dem Schnellaufnahme-Widget, Vox.md zu öffnen und sofort aufzunehmen.",
        "Permite que el widget Grabación rápida abra Vox.md e inicie la grabación de inmediato.",
        "Autorise le widget Enregistrement rapide à ouvrir Vox.md et à démarrer immédiatement.",
        "क्विक रिकॉर्ड विजेट को Vox.md खोलकर तुरंत रिकॉर्डिंग शुरू करने दें।",
        "Izinkan widget Rekam Cepat membuka Vox.md dan langsung mulai merekam.",
        "Consenti al widget Registrazione rapida di aprire Vox.md e iniziare subito a registrare.",
        "クイック録音ウィジェットからVox.mdを開き、すぐに録音を開始できるようにします。",
        "빠른 녹음 위젯이 Vox.md를 열고 즉시 녹음을 시작하도록 허용합니다.",
        "Sta toe dat de widget Snel opnemen Vox.md opent en direct begint met opnemen.",
        "Pozwól widżetowi Szybkie nagrywanie otworzyć Vox.md i natychmiast rozpocząć nagrywanie.",
        "Permite que o widget Gravação Rápida abra o Vox.md e comece a gravar imediatamente.",
        "Разрешить виджету быстрой записи открыть Vox.md и сразу начать запись.",
        "விரைவுப் பதிவு விட்ஜெட் Vox.md-ஐத் திறந்து உடனே பதிவைத் தொடங்க அனுமதி.",
        "อนุญาตให้วิดเจ็ตบันทึกด่วนเปิด Vox.md และเริ่มบันทึกทันที",
        "Hızlı Kayıt araç takımının Vox.md’yi açıp hemen kayda başlamasına izin verir.",
        "Дозволити віджету швидкого запису відкрити Vox.md і негайно почати запис.",
        "فوری ریکارڈ ویجیٹ کو Vox.md کھول کر فوراً ریکارڈنگ شروع کرنے دیں۔",
        "Cho phép tiện ích Ghi âm nhanh mở Vox.md và bắt đầu ghi ngay lập tức.",
        "允许快速录音小组件打开 Vox.md 并立即开始录音。",
        "允許快速錄音小工具開啟 Vox.md 並立即開始錄音。",
    ),
    "Recordings, recording time, and Capture activity": values(
        "التسجيلات ومدة التسجيل ونشاط الالتقاط", "রেকর্ডিং, রেকর্ডিং সময় এবং ক্যাপচার কার্যকলাপ",
        "Aufnahmen, Aufnahmezeit und Erfassungsaktivität", "Grabaciones, tiempo de grabación y actividad de captura",
        "Enregistrements, durée et activité de capture", "रिकॉर्डिंग, रिकॉर्डिंग समय और कैप्चर गतिविधि",
        "Rekaman, durasi rekaman, dan aktivitas tangkapan", "Registrazioni, durata e attività di acquisizione",
        "録音、録音時間、キャプチャ履歴", "녹음, 녹음 시간 및 캡처 활동",
        "Opnamen, opnameduur en vastlegactiviteit", "Nagrania, czas nagrywania i aktywność",
        "Gravações, duração e atividade de captura", "Записи, длительность и активность захвата",
        "பதிவுகள், பதிவு நேரம் மற்றும் பிடிப்பு செயல்பாடு", "รายการบันทึก ระยะเวลา และกิจกรรมจับภาพ",
        "Kayıtlar, kayıt süresi ve yakalama etkinliği", "Записи, тривалість і активність захоплення",
        "ریکارڈنگز، ریکارڈنگ کا وقت اور کیپچر سرگرمی", "Bản ghi, thời lượng và hoạt động ghi nhanh",
        "录音、录音时长和采集活动", "錄音、錄音時間和擷取活動",
    ),
    "Transcription engines, model downloads, and language": values(
        "محركات النسخ الصوتي وتنزيل النماذج واللغة", "ট্রান্সক্রিপশন ইঞ্জিন, মডেল ডাউনলোড এবং ভাষা",
        "Transkriptionssysteme, Modelldownloads und Sprache", "Motores de transcripción, descargas de modelos e idioma",
        "Moteurs de transcription, téléchargements de modèles et langue", "ट्रांसक्रिप्शन इंजन, मॉडल डाउनलोड और भाषा",
        "Mesin transkripsi, unduhan model, dan bahasa", "Motori di trascrizione, download dei modelli e lingua",
        "文字起こしエンジン、モデルのダウンロード、言語", "전사 엔진, 모델 다운로드 및 언어",
        "Transcriptie-engines, modeldownloads en taal", "Systemy transkrypcji, pobieranie modeli i język",
        "Mecanismos de transcrição, downloads de modelos e idioma", "Системы транскрипции, загрузки моделей и язык",
        "உரைமாற்று இயந்திரங்கள், மாதிரி பதிவிறக்கங்கள் மற்றும் மொழி", "เครื่องมือถอดเสียง การดาวน์โหลดโมเดล และภาษา",
        "Transkripsiyon motorları, model indirmeleri ve dil", "Системи транскрипції, завантаження моделей і мова",
        "ٹرانسکرپشن انجن، ماڈل ڈاؤن لوڈ اور زبان", "Công cụ chép lời, tải mô hình và ngôn ngữ",
        "转录引擎、模型下载和语言", "轉錄引擎、模型下載和語言",
    ),
    "Processing, formatting, metadata, and destinations": values(
        "المعالجة والتنسيق والبيانات الوصفية والوجهات", "প্রসেসিং, ফরম্যাটিং, মেটাডেটা এবং গন্তব্য",
        "Verarbeitung, Formatierung, Metadaten und Ziele", "Procesamiento, formato, metadatos y destinos",
        "Traitement, mise en forme, métadonnées et destinations", "प्रोसेसिंग, फ़ॉर्मैटिंग, मेटाडेटा और डेस्टिनेशन",
        "Pemrosesan, pemformatan, metadata, dan tujuan", "Elaborazione, formattazione, metadati e destinazioni",
        "処理、フォーマット、メタデータ、保存先", "처리, 서식, 메타데이터 및 대상",
        "Verwerking, opmaak, metadata en bestemmingen", "Przetwarzanie, formatowanie, metadane i miejsca docelowe",
        "Processamento, formatação, metadados e destinos", "Обработка, форматирование, метаданные и места назначения",
        "செயலாக்கம், வடிவமைப்பு, மேனிலைத் தரவு மற்றும் இலக்குகள்", "การประมวลผล การจัดรูปแบบ เมทาดาทา และปลายทาง",
        "İşleme, biçimlendirme, meta veriler ve hedefler", "Обробка, форматування, метадані та місця призначення",
        "پروسیسنگ، فارمیٹنگ، میٹا ڈیٹا اور منزلیں", "Xử lý, định dạng, siêu dữ liệu và đích",
        "处理、格式、元数据和目标位置", "處理、格式、中繼資料和目的地",
    ),
    "Choose, reorder, and hide quick actions": values(
        "اختر الإجراءات السريعة وأعد ترتيبها أو أخفها", "দ্রুত কাজ বেছে নিন, সাজান এবং লুকান",
        "Schnellaktionen auswählen, neu anordnen und ausblenden", "Elige, reordena y oculta acciones rápidas",
        "Choisissez, réorganisez et masquez les actions rapides", "त्वरित कार्रवाइयाँ चुनें, क्रम बदलें और छिपाएँ",
        "Pilih, urutkan ulang, dan sembunyikan tindakan cepat", "Scegli, riordina e nascondi le azioni rapide",
        "クイックアクションの選択、並べ替え、非表示", "빠른 동작 선택, 순서 변경 및 숨기기",
        "Kies, rangschik en verberg snelle acties", "Wybieraj, zmieniaj kolejność i ukrywaj szybkie czynności",
        "Escolha, reordene e oculte ações rápidas", "Выбирайте, меняйте порядок и скрывайте быстрые действия",
        "விரைவு செயல்களைத் தேர்வு செய்து, வரிசை மாற்றி, மறைக்கவும்", "เลือก จัดลำดับใหม่ และซ่อนการทำงานด่วน",
        "Hızlı eylemleri seçin, yeniden sıralayın ve gizleyin", "Вибирайте, змінюйте порядок і приховуйте швидкі дії",
        "فوری اقدامات منتخب کریں، ترتیب بدلیں اور چھپائیں", "Chọn, sắp xếp lại và ẩn thao tác nhanh",
        "选择、重新排序和隐藏快速操作", "選擇、重新排序和隱藏快速動作",
    ),
    "Automatic uses Apple Speech on supported iOS 26 devices. Whisper and Parakeet downloads are optional local overrides and fallbacks.": values(
        "يستخدم الوضع التلقائي Apple Speech على أجهزة iOS 26 المدعومة. تنزيلات Whisper وParakeet بدائل محلية اختيارية وخيارات احتياطية.",
        "স্বয়ংক্রিয় মোড সমর্থিত iOS 26 ডিভাইসে Apple Speech ব্যবহার করে। Whisper ও Parakeet ঐচ্ছিক স্থানীয় বিকল্প ও ফলব্যাক।",
        "Automatisch nutzt Apple Speech auf unterstützten iOS-26-Geräten. Downloads von Whisper und Parakeet sind optionale lokale Alternativen und Fallbacks.",
        "Automático usa Apple Speech en dispositivos iOS 26 compatibles. Las descargas de Whisper y Parakeet son alternativas y respaldos locales opcionales.",
        "Le mode Automatique utilise Apple Speech sur les appareils iOS 26 compatibles. Les téléchargements Whisper et Parakeet sont des options locales et solutions de repli facultatives.",
        "ऑटोमैटिक मोड समर्थित iOS 26 डिवाइस पर Apple Speech इस्तेमाल करता है। Whisper और Parakeet वैकल्पिक लोकल विकल्प और फ़ॉलबैक हैं।",
        "Otomatis memakai Apple Speech pada perangkat iOS 26 yang didukung. Unduhan Whisper dan Parakeet adalah pilihan lokal dan cadangan opsional.",
        "Automatico usa Apple Speech sui dispositivi iOS 26 supportati. I download di Whisper e Parakeet sono alternative e opzioni di riserva locali.",
        "自動では、対応するiOS 26デバイスでApple Speechを使用します。WhisperとParakeetは、任意でダウンロードできるローカルの代替／予備モデルです。",
        "자동은 지원되는 iOS 26 기기에서 Apple Speech를 사용합니다. Whisper 및 Parakeet 다운로드는 선택 가능한 로컬 대안 및 대체 모델입니다.",
        "Automatisch gebruikt Apple Speech op ondersteunde iOS 26-apparaten. Downloads van Whisper en Parakeet zijn optionele lokale alternatieven en reserveopties.",
        "Tryb automatyczny używa Apple Speech na obsługiwanych urządzeniach iOS 26. Whisper i Parakeet to opcjonalne modele lokalne i zapasowe.",
        "O modo Automático usa Apple Speech em dispositivos compatíveis com iOS 26. Downloads de Whisper e Parakeet são alternativas e reservas locais opcionais.",
        "Автоматический режим использует Apple Speech на поддерживаемых устройствах с iOS 26. Whisper и Parakeet — необязательные локальные и резервные модели.",
        "தானியங்கு முறை ஆதரிக்கப்படும் iOS 26 சாதனங்களில் Apple Speech-ஐப் பயன்படுத்தும். Whisper மற்றும் Parakeet பதிவிறக்கங்கள் விருப்பமான உள்ளூர் மாற்றுகள் மற்றும் காப்பு மாதிரிகள்.",
        "โหมดอัตโนมัติใช้ Apple Speech บนอุปกรณ์ iOS 26 ที่รองรับ ส่วน Whisper และ Parakeet เป็นโมเดลภายในเครื่องและสำรองที่เลือกดาวน์โหลดได้",
        "Otomatik, desteklenen iOS 26 aygıtlarında Apple Speech kullanır. Whisper ve Parakeet indirmeleri isteğe bağlı yerel alternatifler ve yedeklerdir.",
        "Автоматичний режим використовує Apple Speech на підтримуваних пристроях з iOS 26. Whisper і Parakeet — необов’язкові локальні та резервні моделі.",
        "خودکار موڈ معاون iOS 26 ڈیوائسز پر Apple Speech استعمال کرتا ہے۔ Whisper اور Parakeet اختیاری مقامی متبادل اور بیک اپ ماڈلز ہیں۔",
        "Tự động dùng Apple Speech trên thiết bị iOS 26 được hỗ trợ. Whisper và Parakeet là các mô hình cục bộ và dự phòng tùy chọn.",
        "自动模式在受支持的 iOS 26 设备上使用 Apple Speech。Whisper 和 Parakeet 是可选的本地替代及备用模型。",
        "自動模式會在支援的 iOS 26 裝置上使用 Apple Speech。Whisper 和 Parakeet 是可選用的本機替代與備用模型。",
    ),
    "Uses Apple's system-managed, on-device speech recognizer when this device and language support it.": values(
        "يستخدم أداة التعرف على الكلام التي يديرها نظام Apple على الجهاز عندما يدعمها الجهاز واللغة.",
        "ডিভাইস ও ভাষা সমর্থন করলে Apple-এর সিস্টেম-পরিচালিত অন-ডিভাইস স্পিচ রিকগনাইজার ব্যবহার করে।",
        "Verwendet Apples systemverwaltete Spracherkennung auf dem Gerät, wenn Gerät und Sprache sie unterstützen.",
        "Usa el reconocimiento de voz en el dispositivo gestionado por Apple cuando el dispositivo y el idioma son compatibles.",
        "Utilise la reconnaissance vocale sur l’appareil gérée par Apple lorsque l’appareil et la langue sont compatibles.",
        "डिवाइस और भाषा के समर्थित होने पर Apple का सिस्टम-मैनेज्ड ऑन-डिवाइस स्पीच रिकग्नाइज़र इस्तेमाल करता है।",
        "Menggunakan pengenal suara di perangkat yang dikelola sistem Apple jika perangkat dan bahasa mendukungnya.",
        "Usa il riconoscimento vocale sul dispositivo gestito da Apple quando dispositivo e lingua sono supportati.",
        "デバイスと言語が対応している場合、Appleがシステム管理するオンデバイス音声認識を使用します。",
        "기기와 언어가 지원되면 Apple이 시스템에서 관리하는 온디바이스 음성 인식을 사용합니다.",
        "Gebruikt Apples systeembeheerde spraakherkenning op het apparaat wanneer apparaat en taal dit ondersteunen.",
        "Używa systemowego rozpoznawania mowy Apple na urządzeniu, jeśli urządzenie i język są obsługiwane.",
        "Usa o reconhecimento de voz no dispositivo gerenciado pela Apple quando o dispositivo e o idioma são compatíveis.",
        "Использует системное распознавание речи Apple на устройстве, если устройство и язык поддерживаются.",
        "சாதனமும் மொழியும் ஆதரிக்கும்போது Apple அமைப்பு நிர்வகிக்கும் சாதனத்திலுள்ள பேச்சு அறிதலைப் பயன்படுத்தும்.",
        "ใช้การรู้จำเสียงบนอุปกรณ์ที่ระบบ Apple จัดการ เมื่ออุปกรณ์และภาษารองรับ",
        "Aygıt ve dil destekliyorsa Apple’ın sistem tarafından yönetilen aygıt içi konuşma tanımayı kullanır.",
        "Використовує системне розпізнавання мовлення Apple на пристрої, якщо пристрій і мова підтримуються.",
        "ڈیوائس اور زبان معاون ہوں تو Apple کا نظام کے زیر انتظام آن ڈیوائس آواز شناسی استعمال کرتا ہے۔",
        "Dùng nhận dạng giọng nói trên thiết bị do hệ thống Apple quản lý khi thiết bị và ngôn ngữ được hỗ trợ.",
        "当设备和语言受支持时，使用由 Apple 系统管理的设备端语音识别。",
        "當裝置與語言受支援時，使用由 Apple 系統管理的裝置端語音辨識。",
    ),
    "Optional local models you can download and select explicitly.": values(
        "نماذج محلية اختيارية يمكنك تنزيلها وتحديدها.", "ঐচ্ছিক স্থানীয় মডেল, যা ডাউনলোড করে বেছে নিতে পারেন।",
        "Optionale lokale Modelle zum Herunterladen und Auswählen.", "Modelos locales opcionales que puedes descargar y seleccionar.",
        "Modèles locaux facultatifs à télécharger et sélectionner.", "वैकल्पिक लोकल मॉडल जिन्हें डाउनलोड करके चुना जा सकता है।",
        "Model lokal opsional yang dapat diunduh dan dipilih.", "Modelli locali facoltativi da scaricare e selezionare.",
        "ダウンロードして選択できる任意のローカルモデルです。", "다운로드하여 선택할 수 있는 로컬 모델입니다.",
        "Optionele lokale modellen die je kunt downloaden en kiezen.", "Opcjonalne modele lokalne do pobrania i wybrania.",
        "Modelos locais opcionais que você pode baixar e selecionar.", "Необязательные локальные модели, которые можно скачать и выбрать.",
        "பதிவிறக்கம் செய்து தேர்ந்தெடுக்கக்கூடிய விருப்ப உள்ளூர் மாதிரிகள்.", "โมเดลภายในเครื่องที่เลือกดาวน์โหลดและใช้งานได้",
        "İndirip seçebileceğiniz isteğe bağlı yerel modeller.", "Необов’язкові локальні моделі, які можна завантажити й вибрати.",
        "اختیاری مقامی ماڈلز جنہیں آپ ڈاؤن لوڈ کر کے منتخب کر سکتے ہیں۔", "Mô hình cục bộ tùy chọn để tải xuống và lựa chọn.",
        "可下载并选择的本地模型。", "可下載並選用的本機模型。",
    ),
    "Apple Speech unavailable; a downloaded fallback is required": values(
        "Apple Speech غير متاح؛ يلزم تنزيل نموذج احتياطي", "Apple Speech উপলভ্য নয়; একটি বিকল্প মডেল ডাউনলোড করতে হবে",
        "Apple Speech nicht verfügbar; ein geladenes Ersatzmodell ist erforderlich", "Apple Speech no está disponible; se requiere un modelo de respaldo descargado",
        "Apple Speech indisponible ; un modèle de secours téléchargé est requis", "Apple Speech उपलब्ध नहीं; डाउनलोड किया हुआ बैकअप मॉडल आवश्यक है",
        "Apple Speech tidak tersedia; diperlukan model cadangan yang diunduh", "Apple Speech non disponibile; è richiesto un modello di riserva scaricato",
        "Apple Speechは利用できません。ダウンロード済みの予備モデルが必要です", "Apple Speech를 사용할 수 없습니다. 다운로드한 대체 모델이 필요합니다",
        "Apple Speech niet beschikbaar; een gedownload reservemodel is vereist", "Apple Speech niedostępne; wymagany jest pobrany model zapasowy",
        "Apple Speech indisponível; é necessário um modelo de reserva baixado", "Apple Speech недоступен; требуется загруженная резервная модель",
        "Apple Speech கிடைக்கவில்லை; பதிவிறக்கிய காப்பு மாதிரி தேவை", "Apple Speech ใช้ไม่ได้ ต้องดาวน์โหลดโมเดลสำรอง",
        "Apple Speech kullanılamıyor; indirilmiş bir yedek model gerekiyor", "Apple Speech недоступний; потрібна завантажена резервна модель",
        "Apple Speech دستیاب نہیں؛ ڈاؤن لوڈ کیا ہوا بیک اپ ماڈل درکار ہے", "Apple Speech không khả dụng; cần mô hình dự phòng đã tải xuống",
        "Apple Speech 不可用；需要已下载的备用模型", "Apple Speech 無法使用；需要已下載的備用模型",
    ),
    "Clean Prose": values(
        "نص مُنقّح", "পরিমার্জিত গদ্য", "Bereinigter Text", "Prosa depurada",
        "Texte épuré", "सुस्पष्ट गद्य", "Prosa Rapi", "Testo ripulito",
        "文章を整える", "문장 다듬기", "Heldere tekst", "Uporządkowany tekst",
        "Texto aprimorado", "Чистый текст", "செம்மையான உரை", "ปรับข้อความให้อ่านง่าย",
        "Metni Düzenle", "Охайний текст", "بہتر نثر", "Văn bản gọn",
        "润色文本", "潤飾文字",
    ),
    "Keep Original": values(
        "الاحتفاظ بالأصل", "মূলটি রাখুন", "Original beibehalten", "Conservar original",
        "Conserver l’original", "मूल रखें", "Pertahankan Asli", "Mantieni originale",
        "オリジナルを保持", "원본 유지", "Origineel behouden", "Zachowaj oryginał",
        "Manter original", "Сохранить оригинал", "மூலத்தை வைத்திரு", "เก็บต้นฉบับ",
        "Orijinali Koru", "Зберегти оригінал", "اصل برقرار رکھیں", "Giữ nguyên bản",
        "保留原文", "保留原文",
    ),
    "Todo Checklist": values(
        "قائمة مهام", "কাজের চেকলিস্ট", "Aufgabenliste", "Lista de tareas",
        "Liste de tâches", "कार्य सूची", "Daftar Tugas", "Elenco attività",
        "タスクチェックリスト", "할 일 체크리스트", "Takenlijst", "Lista zadań",
        "Lista de tarefas", "Список задач", "பணி சரிபார்ப்புப் பட்டியல்", "รายการสิ่งที่ต้องทำ",
        "Yapılacaklar Listesi", "Список завдань", "کاموں کی فہرست", "Danh sách việc cần làm",
        "任务清单", "工作清單",
    ),
    "Meeting Notes": values(
        "ملاحظات الاجتماع", "মিটিং নোট", "Besprechungsnotizen", "Notas de reunión",
        "Notes de réunion", "मीटिंग नोट्स", "Catatan Rapat", "Note riunione",
        "会議メモ", "회의 메모", "Vergadernotities", "Notatki ze spotkania",
        "Notas da reunião", "Заметки встречи", "கூட்டக் குறிப்புகள்", "บันทึกการประชุม",
        "Toplantı Notları", "Нотатки зустрічі", "میٹنگ نوٹس", "Ghi chú cuộc họp",
        "会议记录", "會議記錄",
    ),
    "Custom Instruction": values(
        "تعليمات مخصصة", "কাস্টম নির্দেশনা", "Eigene Anweisung", "Instrucción personalizada",
        "Instruction personnalisée", "कस्टम निर्देश", "Instruksi Khusus", "Istruzione personalizzata",
        "カスタム指示", "사용자 지정 지침", "Aangepaste instructie", "Własna instrukcja",
        "Instrução personalizada", "Своя инструкция", "தனிப்பயன் வழிமுறை", "คำสั่งกำหนดเอง",
        "Özel Talimat", "Власна інструкція", "حسب ضرورت ہدایت", "Hướng dẫn tùy chỉnh",
        "自定义指令", "自訂指示",
    ),
    "System managed · No app model download": values(
        "يديره النظام · لا يلزم تنزيل نموذج داخل التطبيق",
        "সিস্টেম পরিচালিত · অ্যাপে মডেল ডাউনলোডের প্রয়োজন নেই",
        "Vom System verwaltet · Kein Modell-Download in der App",
        "Gestionado por el sistema · No requiere descargar un modelo en la app",
        "Géré par le système · Aucun modèle à télécharger dans l’app",
        "सिस्टम द्वारा प्रबंधित · ऐप में मॉडल डाउनलोड आवश्यक नहीं",
        "Dikelola sistem · Tidak perlu mengunduh model di aplikasi",
        "Gestito dal sistema · Nessun modello da scaricare nell’app",
        "システム管理 · アプリでのモデルダウンロード不要",
        "시스템 관리 · 앱에서 모델을 다운로드할 필요 없음",
        "Door het systeem beheerd · Geen modeldownload in de app nodig",
        "Zarządzane przez system · Bez pobierania modelu w aplikacji",
        "Gerenciado pelo sistema · Não requer baixar modelo no app",
        "Управляется системой · Загружать модель в приложении не нужно",
        "அமைப்பால் நிர்வகிக்கப்படுகிறது · செயலியில் மாதிரியைப் பதிவிறக்கத் தேவையில்லை",
        "ระบบจัดการ · ไม่ต้องดาวน์โหลดโมเดลในแอป",
        "Sistem tarafından yönetilir · Uygulamada model indirmek gerekmez",
        "Керується системою · Завантажувати модель у застосунку не потрібно",
        "سسٹم کے زیر انتظام · ایپ میں ماڈل ڈاؤن لوڈ کی ضرورت نہیں",
        "Do hệ thống quản lý · Không cần tải mô hình trong ứng dụng",
        "由系统管理 · 无需在 App 中下载模型",
        "由系統管理 · 無需在 App 中下載模型",
    ),
    "↓ DOWNLOAD": values(
        "↓ تنزيل", "↓ ডাউনলোড", "↓ HERUNTERLADEN", "↓ DESCARGAR",
        "↓ TÉLÉCHARGER", "↓ डाउनलोड", "↓ UNDUH", "↓ SCARICA",
        "↓ ダウンロード", "↓ 다운로드", "↓ DOWNLOADEN", "↓ POBIERZ",
        "↓ BAIXAR", "↓ СКАЧАТЬ", "↓ பதிவிறக்கு", "↓ ดาวน์โหลด",
        "↓ İNDİR", "↓ ЗАВАНТАЖИТИ", "↓ ڈاؤن لوڈ", "↓ TẢI XUỐNG",
        "↓ 下载", "↓ 下載",
    ),
    "Waveform": values(
        "موجة صوتية", "তরঙ্গরেখা", "Wellenform", "Forma de onda",
        "Forme d’onde", "वेवफ़ॉर्म", "Gelombang", "Forma d’onda",
        "波形", "파형", "Golfvorm", "Przebieg",
        "Forma de onda", "Форма волны", "அலைவடிவம்", "รูปคลื่น",
        "Dalga Biçimi", "Форма хвилі", "موجی شکل", "Dạng sóng",
        "波形", "波形",
    ),
    "Optimized for English.": values(
        "محسّن للغة الإنجليزية.", "ইংরেজির জন্য অপ্টিমাইজ করা।", "Für Englisch optimiert.", "Optimizado para inglés.",
        "Optimisé pour l’anglais.", "अंग्रेज़ी के लिए अनुकूलित।", "Dioptimalkan untuk bahasa Inggris.", "Ottimizzato per l’inglese.",
        "英語向けに最適化されています。", "영어에 최적화되었습니다.", "Geoptimaliseerd voor Engels.", "Zoptymalizowano dla języka angielskiego.",
        "Otimizado para inglês.", "Оптимизировано для английского языка.", "ஆங்கிலத்திற்காக உகப்பாக்கப்பட்டது.", "ปรับให้เหมาะกับภาษาอังกฤษ",
        "İngilizce için optimize edilmiştir.", "Оптимізовано для англійської мови.", "انگریزی کے لیے بہتر بنایا گیا ہے۔", "Được tối ưu cho tiếng Anh.",
        "针对英语进行了优化。", "針對英文最佳化。",
    ),
    "Supports 25 languages.": values(
        "يدعم 25 لغة.", "২৫টি ভাষা সমর্থন করে।", "Unterstützt 25 Sprachen.", "Admite 25 idiomas.",
        "Prend en charge 25 langues.", "25 भाषाओं का समर्थन करता है।", "Mendukung 25 bahasa.", "Supporta 25 lingue.",
        "25言語に対応しています。", "25개 언어를 지원합니다.", "Ondersteunt 25 talen.", "Obsługuje 25 języków.",
        "Compatível com 25 idiomas.", "Поддерживает 25 языков.", "25 மொழிகளை ஆதரிக்கிறது.", "รองรับ 25 ภาษา",
        "25 dili destekler.", "Підтримує 25 мов.", "25 زبانوں کو سپورٹ کرتا ہے۔", "Hỗ trợ 25 ngôn ngữ.",
        "支持 25 种语言。", "支援 25 種語言。",
    ),
    "Type Markdown, dictate, paste, or drop files anywhere in this window.": values(
        "اكتب Markdown أو أملِ النص أو الصقه أو أفلت الملفات في أي مكان في هذه النافذة.",
        "Markdown লিখুন, ডিক্টেট করুন, পেস্ট করুন বা এই উইন্ডোর যেকোনো স্থানে ফাইল ছেড়ে দিন।",
        "Gib Markdown ein, diktiere, füge Text ein oder lege Dateien irgendwo in diesem Fenster ab.",
        "Escribe Markdown, dicta, pega o suelta archivos en cualquier lugar de esta ventana.",
        "Saisissez du Markdown, dictez, collez ou déposez des fichiers n’importe où dans cette fenêtre.",
        "Markdown लिखें, बोलकर लिखाएँ, पेस्ट करें या इस विंडो में कहीं भी फ़ाइलें छोड़ें।",
        "Ketik Markdown, diktekan, tempel, atau letakkan file di mana saja dalam jendela ini.",
        "Scrivi Markdown, detta, incolla o trascina file in qualsiasi punto della finestra.",
        "Markdownを入力、音声入力、ペーストするか、このウインドウ内にファイルをドロップします。",
        "Markdown을 입력하거나 받아쓰기, 붙여넣기를 사용하고 이 창 어디에나 파일을 놓으세요.",
        "Typ Markdown, dicteer, plak of zet bestanden ergens in dit venster neer.",
        "Wpisz Markdown, dyktuj, wklej lub upuść pliki w dowolnym miejscu tego okna.",
        "Digite Markdown, dite, cole ou solte arquivos em qualquer lugar desta janela.",
        "Введите Markdown, продиктуйте или вставьте текст либо перетащите файлы в это окно.",
        "Markdown-ஐத் தட்டச்சு செய்யவும், குரல்வழி உள்ளிடவும், ஒட்டவும் அல்லது இந்தச் சாளரத்தில் எங்கும் கோப்புகளை விடவும்.",
        "พิมพ์ Markdown ป้อนตามคำบอก วาง หรือลากไฟล์มาวางที่ใดก็ได้ในหน้าต่างนี้",
        "Markdown yazın, dikte edin, yapıştırın veya dosyaları bu pencerenin herhangi bir yerine bırakın.",
        "Введіть Markdown, продиктуйте або вставте текст чи перетягніть файли в це вікно.",
        "Markdown لکھیں، بول کر لکھوائیں، پیسٹ کریں یا اس ونڈو میں کہیں بھی فائلیں چھوڑیں۔",
        "Nhập Markdown, đọc chính tả, dán hoặc thả tệp vào bất kỳ đâu trong cửa sổ này.",
        "输入 Markdown、使用听写、粘贴内容，或将文件拖放到此窗口中的任意位置。",
        "輸入 Markdown、使用聽寫、貼上內容，或將檔案拖放到此視窗中的任意位置。",
    ),
    "A Capture Preset is a complete reusable workflow: what happens to a capture and exactly where it is delivered.": values(
        "إعداد الالتقاط المسبق هو سير عمل كامل قابل لإعادة الاستخدام يحدد ما يحدث للمحتوى وأين يتم تسليمه بالضبط.",
        "ক্যাপচার প্রিসেট হলো সম্পূর্ণ পুনর্ব্যবহারযোগ্য কর্মপ্রবাহ: ক্যাপচারের কী হবে এবং ঠিক কোথায় পাঠানো হবে।",
        "Ein Aufnahme-Preset ist ein vollständig wiederverwendbarer Ablauf: was mit einer Aufnahme geschieht und wohin sie gesendet wird.",
        "Un preajuste de captura es un flujo reutilizable completo: define qué ocurre con una captura y dónde se entrega.",
        "Un préréglage de capture est un flux réutilisable complet : il définit le traitement d’une capture et sa destination.",
        "कैप्चर प्रीसेट एक पूरी तरह पुनः उपयोग योग्य वर्कफ़्लो है: कैप्चर के साथ क्या होता है और उसे कहाँ भेजा जाता है।",
        "Preset Capture adalah alur kerja lengkap yang dapat digunakan kembali: menentukan apa yang terjadi pada tangkapan dan ke mana hasilnya dikirim.",
        "Un preset di acquisizione è un flusso completo e riutilizzabile: stabilisce cosa accade a un’acquisizione e dove viene inviata.",
        "キャプチャプリセットは、キャプチャの処理内容と配信先を定める、再利用可能な一連の設定です。",
        "캡처 프리셋은 캡처 처리 방식과 전달 위치를 정하는 완전한 재사용 워크플로입니다.",
        "Een opnamevoorinstelling is een volledig herbruikbare workflow: wat er met een opname gebeurt en waar die wordt afgeleverd.",
        "Ustawienie przechwytywania to kompletny, wielokrotnego użytku przepływ: określa, co dzieje się z przechwyconą treścią i dokąd trafia.",
        "Uma predefinição de captura é um fluxo completo e reutilizável: define o que acontece com uma captura e onde ela é entregue.",
        "Набор параметров захвата — это готовый повторно используемый процесс: он определяет обработку материала и место доставки.",
        "பிடிப்பு முன்னமைவு என்பது மீண்டும் பயன்படுத்தக்கூடிய முழுமையான செயல்முறை: பிடிப்புக்கு என்ன நடக்கும், அது எங்கு அனுப்பப்படும் என்பதைக் கட்டுப்படுத்தும்.",
        "ค่าที่ตั้งไว้สำหรับการจับข้อมูลคือเวิร์กโฟลว์ที่นำกลับมาใช้ได้ครบถ้วน ซึ่งกำหนดการประมวลผลและปลายทางของข้อมูล",
        "Yakalama Ön Ayarı, bir yakalamaya ne olacağını ve tam olarak nereye gönderileceğini belirleyen yeniden kullanılabilir bir iş akışıdır.",
        "Налаштування захоплення — це готовий повторно використовуваний процес, що визначає обробку матеріалу та місце доставки.",
        "کیپچر پری سیٹ ایک مکمل قابلِ استعمال ورک فلو ہے جو طے کرتا ہے کہ کیپچر کے ساتھ کیا ہو اور اسے کہاں پہنچایا جائے۔",
        "Cấu hình ghi nhanh là quy trình hoàn chỉnh có thể tái sử dụng, quy định cách xử lý nội dung và nơi nội dung được gửi đến.",
        "采集预设是一套可重复使用的完整工作流，用于决定如何处理采集内容以及将其发送到哪里。",
        "擷取預設是一套可重複使用的完整工作流程，用來決定如何處理擷取內容，以及將內容傳送到哪裡。",
    ),
    "Create presets for meetings, journal entries, tasks, ideas, or any setup you use often.": values(
        "أنشئ إعدادات مسبقة للاجتماعات أو إدخالات اليوميات أو المهام أو الأفكار أو أي إعداد تستخدمه كثيرًا.",
        "মিটিং, জার্নাল এন্ট্রি, কাজ, ভাবনা বা নিয়মিত ব্যবহৃত যেকোনো সেটআপের জন্য প্রিসেট তৈরি করুন।",
        "Erstelle Presets für Besprechungen, Tagebucheinträge, Aufgaben, Ideen oder andere häufig genutzte Abläufe.",
        "Crea preajustes para reuniones, entradas de diario, tareas, ideas o cualquier configuración que uses con frecuencia.",
        "Créez des préréglages pour les réunions, le journal, les tâches, les idées ou toute configuration fréquente.",
        "मीटिंग, जर्नल प्रविष्टि, कार्य, विचार या बार-बार उपयोग होने वाली किसी भी व्यवस्था के लिए प्रीसेट बनाएँ।",
        "Buat preset untuk rapat, entri jurnal, tugas, ide, atau pengaturan lain yang sering digunakan.",
        "Crea preset per riunioni, voci di diario, attività, idee o qualsiasi configurazione usata spesso.",
        "会議、日記、タスク、アイデアなど、よく使う用途ごとにプリセットを作成できます。",
        "회의, 일지, 작업, 아이디어 등 자주 사용하는 설정별로 프리셋을 만드세요.",
        "Maak voorinstellingen voor vergaderingen, dagboeknotities, taken, ideeën of andere vaak gebruikte instellingen.",
        "Twórz ustawienia dla spotkań, wpisów w dzienniku, zadań, pomysłów i innych często używanych konfiguracji.",
        "Crie predefinições para reuniões, entradas de diário, tarefas, ideias ou qualquer configuração frequente.",
        "Создавайте наборы параметров для встреч, дневниковых записей, задач, идей и других частых сценариев.",
        "கூட்டங்கள், குறிப்பேட்டுப் பதிவுகள், பணிகள், எண்ணங்கள் அல்லது அடிக்கடி பயன்படுத்தும் அமைப்புகளுக்கு முன்னமைவுகளை உருவாக்குங்கள்.",
        "สร้างค่าที่ตั้งไว้สำหรับการประชุม บันทึกประจำวัน งาน ไอเดีย หรือการตั้งค่าที่ใช้บ่อย",
        "Toplantılar, günlük girdileri, görevler, fikirler veya sık kullandığınız ayarlar için ön ayarlar oluşturun.",
        "Створюйте налаштування для зустрічей, записів у щоденнику, завдань, ідей та інших частих сценаріїв.",
        "میٹنگز، جرنل اندراجات، کاموں، خیالات یا اکثر استعمال ہونے والی کسی بھی ترتیب کے لیے پری سیٹس بنائیں۔",
        "Tạo cấu hình cho cuộc họp, nhật ký, tác vụ, ý tưởng hoặc bất kỳ thiết lập nào bạn thường dùng.",
        "为会议、日记条目、任务、想法或其他常用场景创建预设。",
        "為會議、日記項目、任務、想法或其他常用情境建立預設。",
    ),
})
